{{- if .Values.enableV1Services }}
{{- if .Values.notebooks.ingress.enabled -}}
{{- $fullName := include "renku.notebooks.fullname" . -}}
{{- $servicePort := .Values.notebooks.service.port -}}
{{- $ingressPath := .Values.notebooks.ingress.path -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "renku.notebooks.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.notebooks.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.notebooks.ingress.tls }}
  tls:
  {{- range .Values.notebooks.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.notebooks.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressPath }}
            pathType: Prefix
            backend:
              service:
                name: {{ template "renku.notebooks.fullname" $ }}
                port: 
                  number: {{ $.Values.notebooks.service.port }}
  {{- end }}
{{- end }}
{{- end }}
