{{ if .Values.notebooks.rbac.create }}
{{- $namespaces := list -}}
{{ if .Values.notebooks.sessionsNamespace }}
{{- $namespaces = list .Release.Namespace .Values.notebooks.sessionsNamespace | uniq -}}
{{ else }}
{{- $namespaces = list .Release.Namespace -}}
{{ end }}
{{ range $namespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "renku.notebooks.fullname" $ }}
  namespace: {{ . }}
  labels:
    app: {{ template "renku.notebooks.name" $ }}
    chart: {{ template "renku.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
      - services
      - endpoints
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
      - secrets
    verbs:
      - delete
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - get
      - list
      - watch
      - patch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - update
      - delete
      - patch
  - apiGroups:
      - {{ $.Values.amalthea.crdApiGroup }}
    resources:
      - {{ $.Values.amalthea.crdNames.plural }}
    verbs:
      - create
      - update
      - delete
      - patch
      - list
      - get
      - watch
  - apiGroups:
      - amalthea.dev
    resources:
      - amaltheasessions
    verbs:
      - create
      - update
      - delete
      - patch
      - list
      - get
      - watch
{{ end }}
{{ end }}
