{{- if .Values.enableV1Services }}
{{ if .Values.notebooks.rbac.create }}
{{- $namespaces := list -}}
{{ if .Values.notebooks.sessionsNamespace }}
{{- $namespaces = list .Release.Namespace .Values.notebooks.sessionsNamespace | uniq -}}
{{ else }}
{{- $namespaces = list .Release.Namespace -}}
{{ end }}
{{ range $namespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "renku.notebooks.fullname" $ }}
  namespace: {{ . }}
  labels:
    app: {{ template "renku.notebooks.name" $ }}
    chart: {{ template "renku.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "renku.notebooks.fullname" $ }}
subjects:
  - kind: ServiceAccount
    name: {{ template "renku.notebooks.fullname" $ }}
    namespace: {{ $.Release.Namespace }}
{{ end }}
{{ end }}
{{- end }}
