{{- if .Values.enableV1Services }}
{{- if .Values.notebooks.rbac.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "renku.notebooks.fullname" . }}
  labels:
    app: {{ template "renku.notebooks.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- end -}}
{{- end }}
