{{- if .Values.enableLegacyServices }}
{{- if .Values.notebooks.ssh.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "renku.notebooks.fullname" . }}-ssh
  labels:
    app: {{ template "renku.notebooks.name" . }}-ssh
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  {{- if not .Values.notebooks.ssh.autoscaling.enabled }}
  replicas: {{ .Values.notebooks.ssh.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ template "renku.notebooks.name" . }}-ssh
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "renku.notebooks.name" . }}-ssh
        chart: {{ template "renku.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      {{- with .Values.notebooks.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ if .Values.notebooks.rbac.create }}"{{ template "renku.notebooks.fullname" . }}"{{ else }}"{{ .Values.notebooks.rbac.serviceAccountName }}"{{ end }}
      securityContext:
        fsGroup: 1000
      containers:
        - name: ssh
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
          image: "{{ .Values.notebooks.ssh.image.repository }}:{{ .Values.notebooks.ssh.image.tag }}"
          imagePullPolicy: {{ .Values.notebooks.ssh.image.pullPolicy }}
          ports:
            - name: ssh
              containerPort: 2022
              protocol: TCP
          resources:
            {{- toYaml .Values.notebooks.ssh.resources | nindent 12 }}
          {{- if not (kindIs "invalid" .Values.notebooks.ssh.hostKeySecret) }}
          volumeMounts:
            - name: ssh-host-key
              mountPath: /opt/ssh/ssh_host_keys
              readOnly: true
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if not (kindIs "invalid" .Values.notebooks.ssh.hostKeySecret) }}
      volumes:
        - name: ssh-host-key
          secret:
            secretName: {{ .Values.notebooks.ssh.hostKeySecret | quote }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "renku.notebooks.fullname" . }}-ssh
  labels:
    app: {{ template "renku.notebooks.name" . }}-ssh
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.notebooks.ssh.service.type }}
  ports:
    - name: ssh
      {{- if eq .Values.notebooks.ssh.service.type "NodePort" }}
      nodePort: {{ .Values.notebooks.ssh.service.port }}
      {{- end }}
      port: {{ .Values.notebooks.ssh.service.port }}
      protocol: TCP
      targetPort: ssh
  selector:
    app: {{ template "renku.notebooks.name" . }}-ssh
    release: {{ .Release.Name }}
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "renku.notebooks.fullname" . }}-ssh
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "renku.notebooks.fullname" . }}-ssh
  minReplicas: {{ .Values.notebooks.ssh.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.notebooks.ssh.autoscaling.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.notebooks.ssh.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
{{- end }}
