{{- if .Values.notebooks.tests.enabled }}
apiVersion: v1
kind: Pod
metadata:
  name: "{{ template "renku.notebooks.fullname" . }}-integration-test"
  annotations:
    "helm.sh/hook": test
spec:
  serviceAccountName: {{ template "renku.notebooks.fullname" . }}-test
  containers:
{{- range .Values.notebooks.tests.sessionTypes }}
    - name: {{ printf "%s-integration-test-%s" (include "renku.notebooks.fullname" $) . }}
      image: "{{ $.Values.notebooks.tests.image.repository }}:{{ $.Values.notebooks.tests.image.tag }}"
      imagePullPolicy: {{ $.Values.notebooks.tests.image.pullPolicy }}
      env:
        - name: NB_SESSIONS__INGRESS__HOST
          value: {{ $.Values.notebooks.sessionIngress.host | quote }}
        - name: NB_SESSIONS__OIDC__CLIENT_ID
          value: {{ $.Values.notebooks.oidc.clientId | quote }}
        - name: NB_SESSIONS__OIDC__CLIENT_SECRET
          value: {{ $.Values.notebooks.oidc.clientSecret | quote }}
        - name: NB_SESSIONS__OIDC__TOKEN_URL
          value: {{ $.Values.notebooks.oidc.tokenUrl | quote }}
        - name: NB_SESSIONS__OIDC__AUTH_URL
          value: {{ $.Values.notebooksoidc.authUrl | quote }}
        - name: OIDC_ISSUER
          value: {{ $.Values.notebooks.tests.oidc_issuer | quote }}
        - name: NB_SESSIONS__OIDC__ALLOW_UNVERIFIED_EMAIL
          value: {{ $.Values.notebooks.oidc.allowUnverifiedEmail | quote }}
        - name: NB_GIT__URL
          value: {{ $.Values.notebooks.gitlab.url | quote }}
        - name: NB_GIT__REGISTRY
          value: {{ $.Values.notebooks.gitlab.registry.host | quote }}
        - name: GITLAB_TOKEN
          value: {{ $.Values.notebooks.tests.gitlab_token | quote }}
        - name: NOTEBOOKS_BASE_URL
          value: {{ printf "http://%s" (include "renku.notebooks.fullname" $) }}
        - name: NB_SESSIONS__DEFAULT_IMAGE
          value: "{{ $.Values.notebooks.defaultSessionImage }}"
        - name: NB_SERVER_OPTIONS__DEFAULTS_PATH
          value: /etc/renku-notebooks/server_options/server_defaults.json
        - name: NB_SERVER_OPTIONS__UI_CHOICES_PATH
          value: /etc/renku-notebooks/server_options/server_options.json
        - name: SESSION_TYPE
          value: {{ . | quote }}
        - name: NB_SESSIONS__CULLING__REGISTERED__IDLE_SECONDS
          value: {{ $.Values.notebooks.culling.idleSecondsThreshold.registered | quote }}
        - name: NB_SESSIONS__CULLING__ANONYMOUS__IDLE_SECONDS
          value: {{ $.Values.notebooks.culling.idleSecondsThreshold.anonymous | quote }}
        - name: NB_SESSIONS__CULLING__REGISTERED__HIBERNATED_SECONDS			
          value: {{ $.Values.notebooks.culling.hibernatedSecondsThreshold.registered | quote }}
        - name: NB_SESSIONS__CULLING__REGISTERED__MAX_AGE_SECONDS
          value: {{ $.Values.notebooks.culling.maxAgeSecondsThreshold.registered | quote }}
        - name: NB_SESSIONS__CULLING__ANONYMOUS__MAX_AGE_SECONDS
          value: {{ $.Values.notebooks.culling.maxAgeSecondsThreshold.anonymous | quote }}
        - name: NB_AMALTHEA__GROUP
          value: {{ $.Values.amalthea.crdApiGroup }}
        - name: NB_AMALTHEA__VERSION
          value: {{ $.Values.amalthea.crdApiVersion }}
        - name: NB_AMALTHEA__PLURAL
          value: {{ $.Values.amalthea.crdNames.plural }}
        - name: NB_SESSIONS__INGRESS__ANNOTATIONS
          value: |
            {{- $.Values.notebooks.sessionIngress.annotations | toYaml | nindent 12 }}
        {{ if $.Values.notebooks.sessionsNamespace }}
        - name: NB_K8S__SESSIONS_NAMESPACE
          value: {{ $.Values.notebooks.sessionsNamespace | quote }}
        {{ end }}
        - name: NB_K8S__RENKU_NAMESPACE
          value: {{ $.Release.Namespace | quote }}
        {{- with $.Values.notebooks.sessionNodeSelector }}
        - name: NB_SESSIONS__NODE_SELECTOR
          value: |
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with $.Values.notebooks.sessionAffinity }}
        - name: NB_SESSIONS__AFFINITY
          value: |
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with $.Values.notebooks.sessionTolerations }}
        - name: NB_SESSIONS__TOLERATIONS
          value: |
            {{- toYaml . | nindent 12 }}
        {{- end }}
        - name: NB_SESSIONS__ENFORCE_CPU_LIMITS
          value: {{ $.Values.notebooks.enforceCPULimits | quote }}
        - name: NB_CLOUD_STORAGE__ENABLED
          value: {{ $.Values.notebooks.cloudstorage.enabled | quote }}
        - name: NB_CLOUD_STORAGE__STORAGE_CLASS
          value: {{ .Values.notebooks.cloudstorage.storageClass | default "csi-rclone" | quote }}
        - name: NB_SESSIONS__TERMINATION_WARNING_DURATION_SECONDS
          value: {{ $.Values.notebooks.sessionAutosave.terminationWarningDurationSeconds | quote }}
        - name: NB_VERSION
          value: {{ $.Values.notebooks.image.tag | quote }}
        - name: NB_SESSIONS__GIT_PROXY__RENKU_CLIENT_ID
          value: renku
        - name: NB_DUMMY_STORES
          value: "true"
        - name: NB_SESSIONS__GIT_PROXY__RENKU_CLIENT_SECRET
          value: {{ $.Values.global.gateway.clientSecret | default "renku-client-secret" | quote }}
        - name: NB_KEYCLOAK_REALM
          value: {{ include "renku.keycloak.realm" $ | quote }}
        - name: NB_SESSIONS__SSH__ENABLED
          value: {{ $.Values.notebooks.ssh.enabled | quote }}
        {{- if not (kindIs "invalid" $.Values.notebooks.ssh.hostKeySecret) }}
        - name: NB_SESSIONS__SSH__HOST_KEY_SECRET
          value: {{ $.Values.notebooks.ssh.hostKeySecret | quote }}
        {{- end }}
        - name: NB_DATA_SERVICE_URL
          value: {{ printf "http://%s-data-service/api/data" .Release.Name}}
      volumeMounts:
        - name: server-options
          mountPath: /etc/renku-notebooks/server_options
{{- end }}
  restartPolicy: Never
  volumes:
    - name: server-options
      configMap:
        name: {{ template "renku.notebooks.fullname" . }}-options
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "renku.notebooks.fullname" . }}-test
  labels:
    app: {{ template "renku.notebooks.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
      - services
      - endpoints
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
      - secrets
    verbs:
      - delete
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - update
      - delete
      - patch
  - apiGroups:
      - {{ .Values.amalthea.crdApiGroup }}
    resources:
      - {{ .Values.amalthea.crdNames.plural }}
    verbs:
      - create
      - update
      - delete
      - patch
      - list
      - get
      - watch
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs:
      - create
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "renku.notebooks.fullname" . }}-test
  labels:
    app: {{ template "renku.notebooks.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "renku.notebooks.fullname" . }}-test
subjects:
  - kind: ServiceAccount
    name: {{ template "renku.notebooks.fullname" . }}-test
    namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "renku.notebooks.fullname" . }}-test
  labels:
    app: {{ template "renku.notebooks.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- end }}
