name: 'check PR description'
description: Check the PR description for a string and the following command.
inputs:
  string:
    description: String to check for
    required: true
  pr_ref:
    description: Pull request ID
    required: true
outputs:
  pr-contains-string:
    description: true/false whether the PR description contains the string
    value: ${{ steps.check-string.outputs.pr-contains-string }}
  renku:
    description: renku reference as specified in the command string
    value: ${{ steps.check-string.outputs.renku }}
  renku-core:
    description: renku-core reference as specified in the command string
    value: ${{ steps.check-string.outputs.renku-core }}
  renku-gateway:
    description: renku-gateway reference as specified in the command string
    value: ${{ steps.check-string.outputs.renku-gateway }}
  renku-graph:
    description: renku-graph reference as specified in the command string
    value: ${{ steps.check-string.outputs.renku-graph }}
  renku-notebooks:
    description: renku-notebooks reference as specified in the command string
    value: ${{ steps.check-string.outputs.renku-notebooks }}
  renku-ui:
    description: renku-ui reference as specified in the command string
    value: ${{ steps.check-string.outputs.renku-ui }}
  extra-values:
    description: "extra values passed to helm; separate multiple values with commas: key1=val1,key2=val2"
    value: ${{ steps.check-string.outputs.extra-values }}
  test-enabled:
    description: whether the tests should run or not
    value: ${{ steps.check-string.outputs.test-enabled }}
runs:
  using: "composite"
  steps:
    - id: check-string
      run: |
        echo "Target PR: https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${{ inputs.pr_ref }}"
        pr_text=$(curl -s https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${{ inputs.pr_ref }} | jq '.body')
        pr_contains_string=$(echo $pr_text | jq 'test("${{ inputs.string }}")')
        echo "::set-output name=pr-contains-string::$pr_contains_string"
        echo "String found: $pr_contains_string"
        test_enabled=true
        if [ "$pr_contains_string" = true ] ; then
          command=$(echo $pr_text | jq -r 'split("${{ inputs.string }} ") | last | split("\r\n") | first')
          if [[ $command != *"${{ inputs.string }}"* ]]; then
            echo "Command found: $command"
            match="renku=(\S*)"
            if [[ $command =~ $match ]]; then
              echo "renku reference: ${BASH_REMATCH[1]}"
              echo "::set-output name=renku::@${BASH_REMATCH[1]}"
            fi
            match="renku-core=(\S*)"
            if [[ $command =~ $match ]]; then
              echo "renku-core reference: ${BASH_REMATCH[1]}"
              echo "::set-output name=renku-core::@${BASH_REMATCH[1]}"
            fi
            match="renku-gateway=(\S*)"
            if [[ $command =~ $match ]]; then
              echo "renku-gateway reference: ${BASH_REMATCH[1]}"
              echo "::set-output name=renku-gateway::@${BASH_REMATCH[1]}"
            fi
            match="renku-graph=(\S*)"
            if [[ $command =~ $match ]]; then
              echo "renku-graph reference: ${BASH_REMATCH[1]}"
              echo "::set-output name=renku-graph::@${BASH_REMATCH[1]}"
            fi
            match="renku-notebooks=(\S*)"
            if [[ $command =~ $match ]]; then
              echo "renku-notebooks reference: ${BASH_REMATCH[1]}"
              echo "::set-output name=renku-notebooks::@${BASH_REMATCH[1]}"
            fi
            match="renku-ui=(\S*)"
            if [[ $command =~ $match ]]; then
              echo "renku-ui reference: ${BASH_REMATCH[1]}"
              echo "::set-output name=renku-ui::@${BASH_REMATCH[1]}"
            fi
            match="#notest"
            if [[ $command =~ $match ]]; then
              test_enabled=false
            fi
            match="extra-values=(\S*)"
            if [[ $command =~ $match ]]; then
              echo "extra values: ${BASH_REMATCH[1]}"
              echo "::set-output name=extra-values::${BASH_REMATCH[1]}"
            fi
          else
            echo "No command found"
          fi
        fi
        echo "Test enabled: $test_enabled"
        echo "::set-output name=test-enabled::${test_enabled}"
      shell: bash
