list:
    just --list

test $RUST_LOG="renku_ssh_proxy=debug":
    cargo nextest run --no-fail-fast

clippy:
    cargo clippy --all-targets --fix --allow-dirty --allow-staged && cargo fmt --all

image:
    nix build .#docker && docker load < result

openapi-spec:
    mkdir -p target
    curl -sSL -o target/api.spec.yaml "https://github.com/SwissDataScienceCenter/renku-data-services/raw/refs/heads/salimkayal/feat/ssh-keys_proxy-api/components/renku_data_services/ssh_proxy/api.spec.yaml"

target := 'target/release'

build target=target:
    cargo build --release --bin renku-ssh-proxy --target-dir {{target}}
