# Users schema

# --- !Ups

CREATE TABLE "EVENT_LOG" (
    "EVENT_ID" TEXT NOT NULL,
    "EVENT"    TEXT NOT NULL,
    "CREATED"  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (EVENT_ID)
);

# --- !Downs

DROP TABLE EVENT_LOG;
