{{- if or (gt (int .Values.crc.replicaCount) 1) (and .Values.crc.autoscaling.enabled (gt (int .Values.crc.autoscaling.minReplicas) 1)) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ template "renku.fullname" . }}-crc
  labels:
    app: renku-crc
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  maxUnavailable: 50%
  selector:
    matchLabels:
      app: renku-crc
      release: {{ .Release.Name }}
{{- end }}
