apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.crc.serviceName }}
  labels:
    app: renku-crc
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.crc.service.type }}
  ports:
    - port: {{ .Values.crc.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "renku.name" . }}-crc
    release: {{ .Release.Name }}
