version: 2
build:
  os: ubuntu-22.04
  tools:
    nodejs: "22"
  jobs:
    install:
       - npm --prefix docs clean-install
    build:
      html:
        # Build the site
        - npm --prefix docs run build
        # Copy generated files into Read the Docs directory
        - mkdir --parents $READTHEDOCS_OUTPUT/html/
        - cp --recursive docs/build/* $READTHEDOCS_OUTPUT/html/
