#
# Configuration file for deploying the renku chart on minikube
#

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
    nginx.ingress.kubernetes.io/proxy-body-size: '0' # Adjust to a reasonable value for production to avoid DOS attacks.
    nginx.ingress.kubernetes.io/proxy-request-buffering: 'off' # Needed if GitLab is behind this ingress
  hosts:
  - ""

global:
  gitlab:
    clientSecret: e3ecd740-0892-4610-ad69-c7f4886f4533
    urlPrefix: /gitlab
  gateway:
    clientSecret: 259a72d8-2c40-435f-9e0f-24df7c1a7dbc
    gitlabClientSecret: 4e35410e4116d2280e29c6da6aaaa89fc1ab77364c6352aeb5adbd037d49590a
    cliClientSecret: a49d5d2f0679544b63491a37e0ba2ed08ec4cfc3082f002c8a5a6b81ee201278
  renku:
    version: 'latest'

keycloak:
  createDemoUser: true
  keycloak:
    username: admin

gitlab:
  enabled: true
  oauth:
    autoSignIn: false
  ssh:
    externalPort: 30022
    nodePortService:
      enabled: true
      nodePort: 30022
  registry:
    enabled: true
    exposedAs: NodePort
    externalUrl: http://10.100.123.45:8105/
  sharedRunnersRegistrationToken: 755434ddc0d6344c025dff6af796f2232bbb29c055c668bde9f2aaebd1d37266
  demoUserIsAdmin: true

notebooks:
  securityContext:
    enabled: false
  gitlab:
    registry:
      host: 10.100.123.45:8105
  userSessionPersistentVolumes:
    enabled: true
  oidc:
    allowUnverifiedEmail: true
  sessionIngress:
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/proxy-buffer-size: 8k
      nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/configuration-snippet: |
        more_set_headers "Content-Security-Policy: frame-ancestors 'self' ";
      
runner:
  enabled: true

graph:
  jena:
    users:
      admin:
        password: 94a635b40afc2cba
      renku:
        password: &sparql-password 2b7cd80c595a6e98484c4b8a5ed5e82e

  ## if running gitlab on minikube, set on cmd line with --set graph.gitlab.url
  # gitlab:
  #   url: https://example.com

  webhookService:
    play:
      secret: 79=CRbPUHVQg^kvjQyA>zyZ4s7>ElKz;wW4`<??BlJxO6pQTdlx5M<[jWxWylHx[
    hookToken:
      secret: NjFkNmJiODgyYjk4OWUzNwo=

  triplesGenerator:
    play:
      secret: 3Ie]L>Gr7<ZBb]4lZrm5pgY>Ne5d1L<akIq>QQ3=3_>9kzKd<pEm;]7/eFWh/Wr4

  tokenRepository:
    tokenEncryption:
      secret: MGYxM2JiZTMzY2NhNDg1OQo=

gateway:
  secretKey: 5495ef917488a19d1d4106452c899f5824972acd87edce11fd65e7956bea3bb0
  graph:
    sparql:
      username: admin
      password: *sparql-password

ui:
  canary:
    enabled: false