apiVersion: v1
kind: Secret
metadata:
  name: {{ template "renku.graph.jena.fullname" . }}
  labels:
    app: {{ template "renku.graph.jena.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  jena-users-admin-password: {{ required "Fill in .Values.jena.users.admin.password with `openssl rand -hex 16|base64`" .Values.jena.users.admin.password | b64enc | quote }}
  jena-users-renku-password: {{ required "Fill in .Values.jena.users.renku.password with `openssl rand -hex 16|base64`" .Values.jena.users.renku.password | b64enc | quote }}
