apiVersion: v1
kind: Service
metadata:
  name: {{ template "renku.graph.knowledgeGraph.fullname" . }}
  labels:
    app: {{ template "renku.graph.knowledgeGraph.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
    prometheus.io/port: '9004'
spec:
  type: {{ .Values.graph.knowledgeGraph.service.type }}
  ports:
    - port: {{ .Values.graph.knowledgeGraph.service.port }}
      targetPort: http-kg
      protocol: TCP
      name: http
  selector:
    app: {{ template "renku.graph.knowledgeGraph.name" . }}
    release: {{ .Release.Name }}
