apiVersion: v1
kind: Secret
metadata:
  name: {{ template "renku.graph.tokenRepository.fullname" . }}
  labels:
    app: {{ template "renku.graph.tokenRepository.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  tokenRepository-tokenEncryption-secret: {{ required "Fill in .Values.graph.tokenRepository.tokenEncryption.secret with `openssl rand -hex 8|base64`" .Values.graph.tokenRepository.tokenEncryption.secret | b64enc | quote }}
