{{- if .Values.enableV1Services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "renku.graph.tokenRepository.fullname" . }}
  labels:
    app: {{ template "renku.graph.tokenRepository.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
    prometheus.io/port: '9003'
spec:
  type: {{ .Values.graph.tokenRepository.service.type }}
  ports:
    - port: {{ .Values.graph.tokenRepository.service.port }}
      targetPort: http-token-repo
      protocol: TCP
      name: http
  selector:
    app: {{ template "renku.graph.tokenRepository.name" . }}
    release: {{ .Release.Name }}
{{- end }}
