{{- $tokenRepoSecret := default (include "renku.graph.randHex" 16 | b64enc) .Values.graph.tokenRepository.tokenEncryption.secret | quote }}

{{- if not .Values.graph.tokenRepository.tokenEncryption.secret -}}
{{- $secretName := include "renku.graph.tokenRepository.fullname" . -}}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace $secretName) }}
{{- if $secret }}
{{- $tokenRepoSecret = index $secret.data "tokenRepository-tokenEncryption-secret" }}
{{- end -}}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ template "renku.graph.tokenRepository.fullname" . }}
  labels:
    app: {{ template "renku.graph.tokenRepository.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
stringData:
  tokenRepository-tokenEncryption-secret: {{ $tokenRepoSecret }}
