{{- $hookTokenSecret := default (include "renku.graph.randHex" 16 | b64enc) .Values.graph.webhookService.hookToken.secret | quote }}

{{- if not .Values.graph.webhookService.hookToken.secret -}}
{{- $secretName := include "renku.graph.webhookService.fullname" . -}}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace $secretName) }}
{{- if $secret }}
{{- $hookTokenSecret = index $secret.data "webhookService-hookToken-secret" }}
{{- end -}}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ template "renku.graph.webhookService.fullname" . }}
  labels:
    app: {{ template "renku.graph.webhookService.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
stringData:
  webhookService-hookToken-secret: {{ $hookTokenSecret }}
