apiVersion: v1
kind: Service
metadata:
  name: {{ template "renku.graph.webhookService.fullname" . }}
  labels:
    app: {{ template "renku.graph.webhookService.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
    prometheus.io/port: '9001'
spec:
  type: {{ .Values.graph.webhookService.service.type }}
  ports:
    - port: {{ .Values.graph.webhookService.service.port }}
      targetPort: http-webhook-sv
      protocol: TCP
      name: http
  selector:
    app: {{ template "renku.graph.webhookService.name" . }}
    release: {{ .Release.Name }}
