apiVersion: v1
kind: Secret
metadata:
  name: {{ template "renku.graph.webhookService.fullname" . }}
  labels:
    app: {{ template "renku.graph.webhookService.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  webhookService-hookToken-secret: {{ required "Fill in .Values.graph.webhookService.hookToken.secret with `openssl rand -hex 8|base64`" .Values.graph.webhookService.hookToken.secret | b64enc | quote }}
