apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "renku.search.searchProvision.fullname" . }}
  labels:
    app: {{ template "renku.search.searchProvision.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.search.searchProvision.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ template "renku.search.searchProvision.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "renku.search.searchProvision.name" . }}
        release: {{ .Release.Name }}
        # The label below enables to connect to redis
        {{ .Values.global.redis.clientLabel | toYaml | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      automountServiceAccountToken: {{ .Values.global.debug }}
      containers:
        - name: search-provision
          image: "{{ .Values.search.searchProvision.image.repository }}:{{ .Values.search.searchProvision.image.tag }}"
          imagePullPolicy: {{ .Values.search.searchProvision.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          env:
            - name: RS_REDIS_URL
              value: "redis://{{ .Values.global.redis.host }}:{{ .Values.global.redis.port }}/{{ $.Values.global.redis.dbIndex.events }}"
            - name: RS_REDIS_QUEUE_NAME
              value: "events"
            - name: RS_SOLR_URL
              value: "http://{{ .Values.global.solr.host }}:{{ .Values.global.solr.port }}/solr"
            - name: RS_SOLR_CORE
              value: {{ first .Values.solr.coreNames }}
            - name: RS_SOLR_DEFAULT_COMMIT_WITHIN
              value: "500ms"
            - name: RS_SOLR_LOG_MESSAGE_BODIES
              value: "false"
            - name: JAVA_OPTS
              value: "-Xmx{{ .Values.search.searchProvision.jvmXmx }} -XX:+UseG1GC"
          resources:
            {{- toYaml .Values.search.searchProvision.resources | nindent 12 }}
          volumeMounts:
            {{- include "certificates.volumeMounts.javaCertsGeneral" . | nindent 12 }}
      volumes:
        {{- include "certificates.volumes" . | nindent 8 }}
  {{- with .Values.nodeSelector }}
nodeSelector:
  {{ toYaml . | indent 8 }}
  {{- end }}
  {{- with .Values.affinity }}
affinity:
  {{ toYaml . | indent 8 }}
  {{- end }}
  {{- with .Values.tolerations }}
tolerations:
  {{ toYaml . | indent 8 }}
  {{- end }}
