apiVersion: v1
kind: Service
metadata:
  name: {{ template "renku.search.searchProvision.fullname" . }}
  labels:
    app: {{ template "renku.search.searchProvision.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.search.searchProvision.service.type }}
  # ports:
  #   - port: {{ .Values.search.searchApi.service.port }}
  #     targetPort: http-search-provision
  #     protocol: TCP
  #     name: http
  selector:
    app: {{ template "renku.search.searchProvision.name" . }}
    release: {{ .Release.Name }}
