apiVersion: v1
kind: Service
metadata:
  name: {{ template "renku.search.searchService.fullname" . }}
  labels:
    app: {{ template "renku.search.searchService.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.search.searchApi.service.type }}
  ports:
    - port: {{ .Values.search.searchApi.service.port }}
      targetPort: http-search-api
      protocol: TCP
      name: http
  selector:
    app: {{ template "renku.search.searchApi.name" . }}
    release: {{ .Release.Name }}
