{{- if .Values.ui.server.autoscaling.enabled }}
apiVersion: {{ template "ui-server.autoscaling.apiVersion" . }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "ui-server.fullname" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "ui-server.fullname" . }}
  minReplicas: {{ .Values.ui.server.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.ui.server.autoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.ui.server.autoscaling.cpuUtilization }}
{{- end }}
