{{- if .Values.sshProxy.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "renku.fullname" . }}-ssh-proxy
  labels:
    app: {{ template "renku.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
      - services
      - endpoints
      - persistentvolumeclaims
    verbs:
      - get
      - list
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - get
  - apiGroups:
      - amalthea.dev
    resources:
      - amaltheasessions
    verbs:
      - create
      - update
      - delete
      - patch
      - list
      - get
      - watch
  {{- if .Values.sshProxy.imageBuilders.enabled }}
  - apiGroups:
      - shipwright.io
    resources:
      - buildruns
    verbs:
      - create
      - update
      - delete
      - patch
      - list
      - get
      - watch
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "renku.fullname" . }}-ssh-proxy
  labels:
    app: {{ template "renku.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "renku.fullname" . }}-ssh-proxy
subjects:
  - kind: ServiceAccount
    name: {{ template "renku.fullname" . }}-ssh-proxy
    namespace: {{ .Release.Namespace }}
{{- end -}}
