{{- $openSshHostKey := .Values.sshProxy.openSshHostKey | b64enc | quote }}
{{- $targetIdentity := .Values.sshProxy.targetIdentity | b64enc | quote }}
{{- $renkuFullname := include "renku.fullname" . -}}
{{- $secretName := cat $renkuFullname "-ssh-proxy" | nospace }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    app: {{ template "renku.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade,pre-rollback"
type: Opaque
data:
  # The openssh host key to present to the outside
  openSshHostKey: {{ $openSshHostkey }}
  # The private key to identify at the target host
  targetIdentity: {{ $targetIdentity }}
