{{- $renkuFullname := include "renku.fullname" . -}}
{{- $secretName := cat $renkuFullname "-ssh-proxy" | nospace }}
{{- $openSshHostKey := "" -}}
{{- if .Values.sshProxy.openSshHostKey -}}
{{- $openSshHostKey = .Values.sshProxy.openSshHostKey | b64enc | quote -}}
{{- else -}}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace $secretName) -}}
{{- if $secret -}}
{{- $openSshHostKey = index $secret.data "openSshHostKey" -}}
{{- else -}}
{{- $openSshHostKey = genPrivateKey "ed25519" | b64enc | quote -}}
{{- end -}}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    app: {{ template "renku.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade,pre-rollback"
type: Opaque
data:
  # The openssh host key to present to the outside
  openSshHostKey: {{ $openSshHostKey }}
