apiVersion: v1
kind: Service
metadata:
  name: {{ template "renku.fullname" . }}-ssh-proxy
  labels:
    app: renku-ssh-proxy
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
    prometheus.io/port: '8000'
spec:
  type: {{ .Values.sshProxy.service.type }}
  ports:
    - port: {{ .Values.sshProxy.service.port }}
      targetPort: 2222
      protocol: TCP
      name: ssh
  selector:
    app: {{ template "renku.name" . }}-ssh-proxy
    release: {{ .Release.Name }}
