{{- if or (gt (int .Values.crac.replicaCount) 1) (and .Values.crac.autoscaling.enabled (gt (int .Values.crac.autoscaling.minReplicas) 1)) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ template "renku.fullname" . }}-crac
  labels:
    app: {{ template "renku.name" . }}-crac
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  maxUnavailable: 50%
  selector:
    matchLabels:
      app: {{ template "renku.name" . }}-crac
      release: {{ .Release.Name }}
{{- end }}
