openapi: 3.0.2
info:
  title: Renku Data Services API
  description: |
    This service is the main backend for Renku. It provides information about users, projects,
    cloud storage, access to compute resources and many other things.
  version: v1
servers:
  - url: /api/data
paths:
  /internal/authentication/token:
    post:
      summary: Token endpoint for internal authentication
      description: |
        Supports refreshing internal authentication tokens.
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/PostTokenRequest"
      responses:
        "200":
          description: A new internal access token was generated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PostTokenResponse"
        default:
          $ref: "#/components/responses/Error"
      tags:
        - internal_authentication
components:
  schemas:
    PostTokenRequest:
      type: object
      additionalProperties: true
      properties:
        grant_type:
          $ref: "#/components/schemas/PostTokenGrantType"
        refresh_token:
          type: string
      required:
        - grant_type
        - refresh_token
    PostTokenResponse:
      type: object
      additionalProperties: true
      properties:
        access_token:
          type: string
          example: "some_access_token"
        token_type:
          type: string
          example: "Bearer"
        expires_in:
          type: integer
          example: 600
        refresh_token:
          type: string
          example: "some_refresh_token"
        refresh_expires_in:
          type: integer
          example: 3600
        scope:
          type: string
          example: "api"
      required:
        - access_token
        - token_type
        - expires_in
        - refresh_token
    PostTokenGrantType:
      type: string
      description: A grant type for OAuth 2.0 (see RFC 6749).
      enum:
        - refresh_token
    ErrorResponse:
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: integer
              minimum: 0
              exclusiveMinimum: true
              example: 1404
            detail:
              type: string
              example: "A more detailed optional message showing what the problem was"
            message:
              type: string
              example: "Something went wrong - please try again later"
            trace_id:
              type: string
              example: "ac93950e9e114a55c67fb8e5ef519bbe"
              description: Sentry trace ID for linking to corresponding log entries
          required: ["code", "message"]
      required: ["error"]

  responses:
    Error:
      description: The schema for all 4xx and 5xx responses
      content:
        "application/json":
          schema:
            $ref: "#/components/schemas/ErrorResponse"
