// Package auth provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package auth

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for PostTokenGrantType.
const (
	RefreshToken PostTokenGrantType = "refresh_token"
)

// Valid indicates whether the value is a known member of the PostTokenGrantType enum.
func (e PostTokenGrantType) Valid() bool {
	switch e {
	case RefreshToken:
		return true
	default:
		return false
	}
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error struct {
		// Code Example: 1404
		Code int `json:"code"`

		// Detail Example: A more detailed optional message showing what the problem was
		Detail *string `json:"detail,omitempty"`

		// Message Example: Something went wrong - please try again later
		Message string `json:"message"`

		// TraceId Sentry trace ID for linking to corresponding log entries
		//
		// Example: ac93950e9e114a55c67fb8e5ef519bbe
		TraceId *string `json:"trace_id,omitempty"`
	} `json:"error"`
}

// PostTokenGrantType A grant type for OAuth 2.0 (see RFC 6749).
type PostTokenGrantType string

// PostTokenRequest defines model for PostTokenRequest.
type PostTokenRequest struct {
	// GrantType A grant type for OAuth 2.0 (see RFC 6749).
	GrantType            PostTokenGrantType     `json:"grant_type"`
	RefreshToken         string                 `json:"refresh_token"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// PostTokenResponse defines model for PostTokenResponse.
type PostTokenResponse struct {
	// AccessToken Example: some_access_token
	AccessToken string `json:"access_token"`

	// ExpiresIn Example: 600
	ExpiresIn int `json:"expires_in"`

	// RefreshExpiresIn Example: 3600
	RefreshExpiresIn *int `json:"refresh_expires_in,omitempty"`

	// RefreshToken Example: some_refresh_token
	RefreshToken string `json:"refresh_token"`

	// Scope Example: api
	Scope *string `json:"scope,omitempty"`

	// TokenType Example: Bearer
	TokenType            string                 `json:"token_type"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// Error defines model for Error.
type Error = ErrorResponse

// PostInternalAuthenticationTokenFormdataRequestBody defines body for PostInternalAuthenticationToken for application/x-www-form-urlencoded ContentType.
type PostInternalAuthenticationTokenFormdataRequestBody = PostTokenRequest

// Getter for additional properties for PostTokenRequest. Returns the specified
// element and whether it was found
func (a PostTokenRequest) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for PostTokenRequest
func (a *PostTokenRequest) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for PostTokenRequest to handle AdditionalProperties
func (a *PostTokenRequest) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["grant_type"]; found {
		err = json.Unmarshal(raw, &a.GrantType)
		if err != nil {
			return fmt.Errorf("error reading 'grant_type': %w", err)
		}
		delete(object, "grant_type")
	}

	if raw, found := object["refresh_token"]; found {
		err = json.Unmarshal(raw, &a.RefreshToken)
		if err != nil {
			return fmt.Errorf("error reading 'refresh_token': %w", err)
		}
		delete(object, "refresh_token")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for PostTokenRequest to handle AdditionalProperties
func (a PostTokenRequest) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["grant_type"], err = json.Marshal(a.GrantType)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'grant_type': %w", err)
	}

	object["refresh_token"], err = json.Marshal(a.RefreshToken)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'refresh_token': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for PostTokenResponse. Returns the specified
// element and whether it was found
func (a PostTokenResponse) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for PostTokenResponse
func (a *PostTokenResponse) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for PostTokenResponse to handle AdditionalProperties
func (a *PostTokenResponse) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["access_token"]; found {
		err = json.Unmarshal(raw, &a.AccessToken)
		if err != nil {
			return fmt.Errorf("error reading 'access_token': %w", err)
		}
		delete(object, "access_token")
	}

	if raw, found := object["expires_in"]; found {
		err = json.Unmarshal(raw, &a.ExpiresIn)
		if err != nil {
			return fmt.Errorf("error reading 'expires_in': %w", err)
		}
		delete(object, "expires_in")
	}

	if raw, found := object["refresh_expires_in"]; found {
		err = json.Unmarshal(raw, &a.RefreshExpiresIn)
		if err != nil {
			return fmt.Errorf("error reading 'refresh_expires_in': %w", err)
		}
		delete(object, "refresh_expires_in")
	}

	if raw, found := object["refresh_token"]; found {
		err = json.Unmarshal(raw, &a.RefreshToken)
		if err != nil {
			return fmt.Errorf("error reading 'refresh_token': %w", err)
		}
		delete(object, "refresh_token")
	}

	if raw, found := object["scope"]; found {
		err = json.Unmarshal(raw, &a.Scope)
		if err != nil {
			return fmt.Errorf("error reading 'scope': %w", err)
		}
		delete(object, "scope")
	}

	if raw, found := object["token_type"]; found {
		err = json.Unmarshal(raw, &a.TokenType)
		if err != nil {
			return fmt.Errorf("error reading 'token_type': %w", err)
		}
		delete(object, "token_type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for PostTokenResponse to handle AdditionalProperties
func (a PostTokenResponse) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["access_token"], err = json.Marshal(a.AccessToken)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'access_token': %w", err)
	}

	object["expires_in"], err = json.Marshal(a.ExpiresIn)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'expires_in': %w", err)
	}

	if a.RefreshExpiresIn != nil {
		object["refresh_expires_in"], err = json.Marshal(a.RefreshExpiresIn)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'refresh_expires_in': %w", err)
		}
	}

	object["refresh_token"], err = json.Marshal(a.RefreshToken)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'refresh_token': %w", err)
	}

	if a.Scope != nil {
		object["scope"], err = json.Marshal(a.Scope)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'scope': %w", err)
		}
	}

	object["token_type"], err = json.Marshal(a.TokenType)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'token_type': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// PostInternalAuthenticationTokenWithBody Token endpoint for internal authentication
	//
	// Supports refreshing internal authentication tokens.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /internal/authentication/token (the `PostInternalAuthenticationToken` operationId).
	PostInternalAuthenticationTokenWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostInternalAuthenticationTokenWithFormdataBody Token endpoint for internal authentication
	//
	// Supports refreshing internal authentication tokens.
	//
	// Takes a body of the `application/x-www-form-urlencoded` content type.
	//
	// Corresponds with POST /internal/authentication/token (the `PostInternalAuthenticationToken` operationId).
	PostInternalAuthenticationTokenWithFormdataBody(ctx context.Context, body PostInternalAuthenticationTokenFormdataRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// PostInternalAuthenticationTokenWithBody Token endpoint for internal authentication
//
// Supports refreshing internal authentication tokens.
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /internal/authentication/token (the `PostInternalAuthenticationToken` operationId).
func (c *Client) PostInternalAuthenticationTokenWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostInternalAuthenticationTokenRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostInternalAuthenticationTokenWithFormdataBody Token endpoint for internal authentication
//
// Supports refreshing internal authentication tokens.
//
// Takes a body of the `application/x-www-form-urlencoded` content type.
//
// Corresponds with POST /internal/authentication/token (the `PostInternalAuthenticationToken` operationId).
func (c *Client) PostInternalAuthenticationTokenWithFormdataBody(ctx context.Context, body PostInternalAuthenticationTokenFormdataRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostInternalAuthenticationTokenRequestWithFormdataBody(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPostInternalAuthenticationTokenRequestWithFormdataBody calls the generic PostInternalAuthenticationToken builder with application/x-www-form-urlencoded body
func NewPostInternalAuthenticationTokenRequestWithFormdataBody(server string, body PostInternalAuthenticationTokenFormdataRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	bodyStr, err := runtime.MarshalForm(body, nil)
	if err != nil {
		return nil, err
	}
	bodyReader = strings.NewReader(bodyStr.Encode())
	return NewPostInternalAuthenticationTokenRequestWithBody(server, "application/x-www-form-urlencoded", bodyReader)
}

// NewPostInternalAuthenticationTokenRequestWithBody constructs an http.Request for the PostInternalAuthenticationToken method, with any body, and a specified content type
func NewPostInternalAuthenticationTokenRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/internal/authentication/token")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// PostInternalAuthenticationTokenWithBodyWithResponse Token endpoint for internal authentication
	//
	// Supports refreshing internal authentication tokens.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /internal/authentication/token (the `PostInternalAuthenticationToken` operationId).
	PostInternalAuthenticationTokenWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostInternalAuthenticationTokenResponse, error)

	// PostInternalAuthenticationTokenWithFormdataBodyWithResponse Token endpoint for internal authentication
	//
	// Supports refreshing internal authentication tokens.
	//
	// Takes a body of the `application/x-www-form-urlencoded` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /internal/authentication/token (the `PostInternalAuthenticationToken` operationId).
	PostInternalAuthenticationTokenWithFormdataBodyWithResponse(ctx context.Context, body PostInternalAuthenticationTokenFormdataRequestBody, reqEditors ...RequestEditorFn) (*PostInternalAuthenticationTokenResponse, error)
}

type PostInternalAuthenticationTokenResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *PostTokenResponse
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r PostInternalAuthenticationTokenResponse) GetJSON200() *PostTokenResponse {
	return r.JSON200
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r PostInternalAuthenticationTokenResponse) GetJSONDefault() *Error {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r PostInternalAuthenticationTokenResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r PostInternalAuthenticationTokenResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostInternalAuthenticationTokenResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostInternalAuthenticationTokenResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// PostInternalAuthenticationTokenWithBodyWithResponse Token endpoint for internal authentication
//
// Supports refreshing internal authentication tokens.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /internal/authentication/token (the `PostInternalAuthenticationToken` operationId).
func (c *ClientWithResponses) PostInternalAuthenticationTokenWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostInternalAuthenticationTokenResponse, error) {
	rsp, err := c.PostInternalAuthenticationTokenWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostInternalAuthenticationTokenResponse(rsp)
}

// PostInternalAuthenticationTokenWithFormdataBodyWithResponse Token endpoint for internal authentication
//
// Supports refreshing internal authentication tokens.
//
// Takes a body of the `application/x-www-form-urlencoded` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /internal/authentication/token (the `PostInternalAuthenticationToken` operationId).
func (c *ClientWithResponses) PostInternalAuthenticationTokenWithFormdataBodyWithResponse(ctx context.Context, body PostInternalAuthenticationTokenFormdataRequestBody, reqEditors ...RequestEditorFn) (*PostInternalAuthenticationTokenResponse, error) {
	rsp, err := c.PostInternalAuthenticationTokenWithFormdataBody(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostInternalAuthenticationTokenResponse(rsp)
}

// ParsePostInternalAuthenticationTokenResponse parses an HTTP response from a PostInternalAuthenticationTokenWithResponse call
func ParsePostInternalAuthenticationTokenResponse(rsp *http.Response) (*PostInternalAuthenticationTokenResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostInternalAuthenticationTokenResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PostTokenResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"rFZLj9s2EP4rA7aHFtDa3oc3Xd2cpi18KLrY9S1ZGLQ0lhhLJDOk/IDh/14M6Zf8yOaQm0TOfDPfPLkW",
	"mamt0ai9E+laEDprtMPw8xeRIf7IjPaoPX9KayuVSa+M7n51RvOZy0qsJX/9SjgVqfile0DtxlvXDWgv",
	"W3yx2WwSkaPLSFkGE6kYlQhRGKaGQFYVPCyXIHUO/eUSDq6x6hZ17+YeOF0LS8YieRVZ4I5F+zgzeRDG",
	"paxthSK9feg9JAKXWdU4Ncd/lVZ1U4vUU4OJqHe/vUT4lUWRCqU9FkgiEPFSVS04MYDaEEK8whxM4Ckr",
	"qNE5WSC40iyULmBRSg++RLBkJhXWsJBO7K04T0oXbGSr17byamr0ZYBB7WFBRhdwA7ZC6RA8rUAWUmmo",
	"pEe6hOpJZjhWOcO28/GKmvWDAAw/haRUSs/YmDeQGYopyfmgMgWwPEc3OfJPZk/3T/0ePuHt7YPs97PH",
	"D9PJH9jHaf/2aTLBc5c2iSD81ijCXKSfY54O5N/28mbyFTN/Jh/TfS6WiGfj/MjMUP9DUvtRuD7lPICC",
	"L4GVA+H/Bo0v4a7Tg98cIrz8/Sc8fnh4+r3DLDUXxGdBOCV05dgz+JHpQ5D3pl/wW4MudlKeq1gRz0eF",
	"GautXarBpbHfOvy9HrtAMYTn2L90/U7Ej8wlV7ldCOtxC/44OZll6NzBt0PpOFPjuHV9IbK4tIrQjVVb",
	"+bF3sU93bK5o3b+jds3J9v0FL11m7EnjSqsutiND7HN9EP+Iki418EnuTsN1QGuF6v28MrDSU3PeIqNS",
	"OXBIc5UhKBcmV80jZiKzGeo8tM0L6lnTgaHnoTZXOTpgNKrD5gA5MY2HxiG5hCXYpku+6KwyTQ7OG5IF",
	"JhDZxGFT28YjLwHTUIYurIVa6hUYXyJBmIGu8yWwVj7ELDgBn6SX8Br9dTB4HopEzJFcZDO/5agbi5oT",
	"kor7Tq9zJxJhpS9DfXa5DkjLqisbX6L2u+23LwZrYkOfTM/GWkPewTbSPCR3UNCGggC1dZ57I5wOc5GG",
	"5hputQYtpdE2xRQnykeTr76zqpc3i8XihhNw01CFmqdq/uO7+2x+bdqFx40dDo5eD3e93k97O5zPmAvv",
	"hwFoXBzFeFc8M9S8UqFAzaHFPG7sqWwqf83wnkl8tsQnR1PXklbcAgETdW6N0j4U/JXUcjXKwnFr7iTG",
	"JxJvgQo3FBILrkVDlUhFV1rVzaWXYvO2+T8AAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
