apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "renku.fullname" . }}-data-service-messages
  labels:
    app: renku-data-service-messages
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ template "renku.chart" . }}
spec:
  replicas: 1
  strategy: 
    {{- toYaml .Values.dataService.updateStrategy | nindent 4 }}
  selector:
    matchLabels:
      app: renku-data-service-messages
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:          
        app: renku-data-service-messages
        release: {{ .Release.Name }}
        {{ .Values.global.redis.clientLabel | toYaml | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        {{- include "certificates.initContainer" . | nindent 8 }}
      containers:
        - name: data-service-messages
          image: "{{ .Values.dataService.backgroundJobs.image.repository }}:{{ .Values.dataService.backgroundJobs.image.tag }}"
          imagePullPolicy: IfNotPresent
          args: ["send_messages"]
          env:
            - name: DB_HOST
              value: {{ template "postgresql.fullname" . }}
            - name: DB_USER
              value: {{ .Values.global.db.common.username }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.db.common.passwordSecretName }}
                  key: password
            - name: REDIS_HOST
              value: {{ .Values.global.redis.host | quote }}
            - name: REDIS_PORT
              value: {{ .Values.global.redis.port | quote }}
            - name: REDIS_DATABASE
              value: {{ .Values.global.redis.dbIndex.events| quote }}
            - name: REDIS_IS_SENTINEL
              value: {{ .Values.global.redis.sentinel.enabled | quote }}
            - name: REDIS_MASTER_SET
              value: {{ .Values.global.redis.sentinel.masterSet | quote }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.redis.existingSecret }}
                  key: {{ .Values.global.redis.existingSecretPasswordKey }}
            {{- include "certificates.env.python" . | nindent 12 }}
            {{- include "certificates.env.grpc" . | nindent 12 }}
          volumeMounts:
            {{- include "certificates.volumeMounts.system" . | nindent 12 }}
      volumes:
        {{- include "certificates.volumes" . | nindent 8 }}
