apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "renku.fullname" . }}-data-service-messages
  labels:
    app: data-service-messages
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ template "renku.chart" . }}
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:          
            app: data-service-messages
            {{ .Values.global.redis.clientLabel | toYaml | nindent 12 }}
        spec:
          initContainers:
            {{- include "certificates.initContainer" . | nindent 12 }}
          containers:
            - name: data-service-messages
              image: "{{ .Values.dataService.backgroundJobs.image.repository }}:{{ .Values.dataService.backgroundJobs.image.tag }}"
              imagePullPolicy: IfNotPresent
              args: ["send_messages"]
              env:
                - name: DB_HOST
                  value: {{ template "postgresql.fullname" . }}
                - name: DB_USER
                  value: {{ .Values.global.db.common.username }}
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.global.db.common.passwordSecretName }}
                      key: password
                - name: REDIS_HOST
                  value: {{ .Values.global.redis.host | quote }}
                - name: REDIS_PORT
                  value: {{ .Values.global.redis.port | quote }}
                - name: REDIS_DATABASE
                  value: {{ .Values.global.redis.dbIndex.events| quote }}
                - name: REDIS_IS_SENTINEL
                  value: {{ .Values.global.redis.sentinel.enabled | quote }}
                - name: REDIS_MASTER_SET
                  value: {{ .Values.global.redis.sentinel.masterSet | quote }}
                - name: REDIS_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.global.redis.existingSecret }}
                      key: {{ .Values.global.redis.existingSecretPasswordKey }}
                {{- include "certificates.env.python" . | nindent 16 }}
                {{- include "certificates.env.grpc" . | nindent 16 }}
              volumeMounts:
                {{- include "certificates.volumeMounts.system" . | nindent 16 }}
          restartPolicy: Never
          volumes:
            {{- include "certificates.volumes" . | nindent 12 }}
