// Package session_runners provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package session_runners

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for SessionRunnerContactPostStatus.
const (
	SessionRunnerContactPostStatusNotReady SessionRunnerContactPostStatus = "not_ready"
	SessionRunnerContactPostStatusReady    SessionRunnerContactPostStatus = "ready"
)

// Valid indicates whether the value is a known member of the SessionRunnerContactPostStatus enum.
func (e SessionRunnerContactPostStatus) Valid() bool {
	switch e {
	case SessionRunnerContactPostStatusNotReady:
		return true
	case SessionRunnerContactPostStatusReady:
		return true
	default:
		return false
	}
}

// Defines values for SessionRunnerStatus.
const (
	SessionRunnerStatusInitializing   SessionRunnerStatus = "initializing"
	SessionRunnerStatusNeverContacted SessionRunnerStatus = "never_contacted"
	SessionRunnerStatusNotReady       SessionRunnerStatus = "not_ready"
	SessionRunnerStatusReady          SessionRunnerStatus = "ready"
)

// Valid indicates whether the value is a known member of the SessionRunnerStatus enum.
func (e SessionRunnerStatus) Valid() bool {
	switch e {
	case SessionRunnerStatusInitializing:
		return true
	case SessionRunnerStatusNeverContacted:
		return true
	case SessionRunnerStatusNotReady:
		return true
	case SessionRunnerStatusReady:
		return true
	default:
		return false
	}
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error struct {
		// Code Example: 1404
		Code int `json:"code"`

		// Detail Example: A more detailed optional message showing what the problem was
		Detail *string `json:"detail,omitempty"`

		// Message Example: Something went wrong - please try again later
		Message string `json:"message"`

		// TraceId Sentry trace ID for linking to corresponding log entries
		//
		// Example: ac93950e9e114a55c67fb8e5ef519bbe
		TraceId *string `json:"trace_id,omitempty"`
	} `json:"error"`
}

// SessionRunner A session runner
type SessionRunner struct {
	// Id ULID identifier
	Id                Ulid    `json:"id"`
	RegistrationToken *string `json:"registration_token,omitempty"`
	ResourcePoolId    int     `json:"resource_pool_id"`

	// Status The status of a session runner
	Status SessionRunnerStatus `json:"status"`
}

// SessionRunnerAssignedSession defines model for SessionRunnerAssignedSession.
type SessionRunnerAssignedSession = string

// SessionRunnerAssignedSessions The list of sessions assigned to a runner
type SessionRunnerAssignedSessions = []SessionRunnerAssignedSession

// SessionRunnerContactPost Data sent when a session runner contacts the API
type SessionRunnerContactPost struct {
	Status SessionRunnerContactPostStatus `json:"status"`
}

// SessionRunnerContactPostStatus defines model for SessionRunnerContactPost.Status.
type SessionRunnerContactPostStatus string

// SessionRunnerContactResponse Data sent back when a session runner contacts the API
type SessionRunnerContactResponse struct {
	// Sessions The list of sessions assigned to a runner
	Sessions *SessionRunnerAssignedSessions `json:"sessions,omitempty"`
}

// SessionRunnerPost Data required to create a session runner
type SessionRunnerPost struct {
	ResourcePoolId int `json:"resource_pool_id"`
}

// SessionRunnerRegisterPost Data required to register a session runner
type SessionRunnerRegisterPost struct {
	RegistrationToken string `json:"registration_token"`
}

// SessionRunnerRegisterResponse The result of registering a session runner
type SessionRunnerRegisterResponse struct {
	Auth SessionRunnerRegisterResponse_Auth `json:"auth"`

	// Runner A session runner
	Runner SessionRunner `json:"runner"`
}

// SessionRunnerRegisterResponse_Auth defines model for SessionRunnerRegisterResponse.Auth.
type SessionRunnerRegisterResponse_Auth struct {
	// AccessToken Example: some_access_token
	AccessToken string `json:"access_token"`

	// ExpiresIn Example: 600
	ExpiresIn int `json:"expires_in"`

	// RefreshExpiresIn Example: 3600
	RefreshExpiresIn *int `json:"refresh_expires_in,omitempty"`

	// RefreshToken Example: some_refresh_token
	RefreshToken string `json:"refresh_token"`

	// Scope Example: api
	Scope *string `json:"scope,omitempty"`

	// TokenType Example: Bearer
	TokenType            string                 `json:"token_type"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// SessionRunnerStatus The status of a session runner
type SessionRunnerStatus string

// Ulid ULID identifier
type Ulid = string

// Error defines model for Error.
type Error = ErrorResponse

// PostSessionRunnersJSONRequestBody defines body for PostSessionRunners for application/json ContentType.
type PostSessionRunnersJSONRequestBody = SessionRunnerPost

// PostSessionRunnersRegisterJSONRequestBody defines body for PostSessionRunnersRegister for application/json ContentType.
type PostSessionRunnersRegisterJSONRequestBody = SessionRunnerRegisterPost

// PostSessionRunnersSessionRunnerIdContactJSONRequestBody defines body for PostSessionRunnersSessionRunnerIdContact for application/json ContentType.
type PostSessionRunnersSessionRunnerIdContactJSONRequestBody = SessionRunnerContactPost

// Getter for additional properties for SessionRunnerRegisterResponse_Auth. Returns the specified
// element and whether it was found
func (a SessionRunnerRegisterResponse_Auth) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for SessionRunnerRegisterResponse_Auth
func (a *SessionRunnerRegisterResponse_Auth) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for SessionRunnerRegisterResponse_Auth to handle AdditionalProperties
func (a *SessionRunnerRegisterResponse_Auth) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["access_token"]; found {
		err = json.Unmarshal(raw, &a.AccessToken)
		if err != nil {
			return fmt.Errorf("error reading 'access_token': %w", err)
		}
		delete(object, "access_token")
	}

	if raw, found := object["expires_in"]; found {
		err = json.Unmarshal(raw, &a.ExpiresIn)
		if err != nil {
			return fmt.Errorf("error reading 'expires_in': %w", err)
		}
		delete(object, "expires_in")
	}

	if raw, found := object["refresh_expires_in"]; found {
		err = json.Unmarshal(raw, &a.RefreshExpiresIn)
		if err != nil {
			return fmt.Errorf("error reading 'refresh_expires_in': %w", err)
		}
		delete(object, "refresh_expires_in")
	}

	if raw, found := object["refresh_token"]; found {
		err = json.Unmarshal(raw, &a.RefreshToken)
		if err != nil {
			return fmt.Errorf("error reading 'refresh_token': %w", err)
		}
		delete(object, "refresh_token")
	}

	if raw, found := object["scope"]; found {
		err = json.Unmarshal(raw, &a.Scope)
		if err != nil {
			return fmt.Errorf("error reading 'scope': %w", err)
		}
		delete(object, "scope")
	}

	if raw, found := object["token_type"]; found {
		err = json.Unmarshal(raw, &a.TokenType)
		if err != nil {
			return fmt.Errorf("error reading 'token_type': %w", err)
		}
		delete(object, "token_type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for SessionRunnerRegisterResponse_Auth to handle AdditionalProperties
func (a SessionRunnerRegisterResponse_Auth) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["access_token"], err = json.Marshal(a.AccessToken)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'access_token': %w", err)
	}

	object["expires_in"], err = json.Marshal(a.ExpiresIn)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'expires_in': %w", err)
	}

	if a.RefreshExpiresIn != nil {
		object["refresh_expires_in"], err = json.Marshal(a.RefreshExpiresIn)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'refresh_expires_in': %w", err)
		}
	}

	object["refresh_token"], err = json.Marshal(a.RefreshToken)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'refresh_token': %w", err)
	}

	if a.Scope != nil {
		object["scope"], err = json.Marshal(a.Scope)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'scope': %w", err)
		}
	}

	object["token_type"], err = json.Marshal(a.TokenType)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'token_type': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// PostSessionRunnersWithBody Create a new session runner
	//
	// TODO.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /session_runners (the `PostSessionRunners` operationId).
	PostSessionRunnersWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostSessionRunners Create a new session runner
	//
	// TODO.
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /session_runners (the `PostSessionRunners` operationId).
	PostSessionRunners(ctx context.Context, body PostSessionRunnersJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostSessionRunnersRegisterWithBody Register a session runner
	//
	// TODO.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /session_runners/register (the `PostSessionRunnersRegister` operationId).
	PostSessionRunnersRegisterWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostSessionRunnersRegister Register a session runner
	//
	// TODO.
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /session_runners/register (the `PostSessionRunnersRegister` operationId).
	PostSessionRunnersRegister(ctx context.Context, body PostSessionRunnersRegisterJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetSessionRunnersSessionRunnerId Get a session runner
	//
	// TODO.
	//
	// Corresponds with GET /session_runners/{session_runner_id} (the `GetSessionRunnersSessionRunnerId` operationId).
	GetSessionRunnersSessionRunnerId(ctx context.Context, sessionRunnerId Ulid, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostSessionRunnersSessionRunnerIdContactWithBody Contact endpoint for session runners
	//
	// TODO.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /session_runners/{session_runner_id}/contact (the `PostSessionRunnersSessionRunnerIdContact` operationId).
	PostSessionRunnersSessionRunnerIdContactWithBody(ctx context.Context, sessionRunnerId Ulid, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostSessionRunnersSessionRunnerIdContact Contact endpoint for session runners
	//
	// TODO.
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /session_runners/{session_runner_id}/contact (the `PostSessionRunnersSessionRunnerIdContact` operationId).
	PostSessionRunnersSessionRunnerIdContact(ctx context.Context, sessionRunnerId Ulid, body PostSessionRunnersSessionRunnerIdContactJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// PostSessionRunnersWithBody Create a new session runner
//
// TODO.
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /session_runners (the `PostSessionRunners` operationId).
func (c *Client) PostSessionRunnersWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostSessionRunnersRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostSessionRunners Create a new session runner
//
// TODO.
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /session_runners (the `PostSessionRunners` operationId).
func (c *Client) PostSessionRunners(ctx context.Context, body PostSessionRunnersJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostSessionRunnersRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostSessionRunnersRegisterWithBody Register a session runner
//
// TODO.
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /session_runners/register (the `PostSessionRunnersRegister` operationId).
func (c *Client) PostSessionRunnersRegisterWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostSessionRunnersRegisterRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostSessionRunnersRegister Register a session runner
//
// TODO.
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /session_runners/register (the `PostSessionRunnersRegister` operationId).
func (c *Client) PostSessionRunnersRegister(ctx context.Context, body PostSessionRunnersRegisterJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostSessionRunnersRegisterRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetSessionRunnersSessionRunnerId Get a session runner
//
// TODO.
//
// Corresponds with GET /session_runners/{session_runner_id} (the `GetSessionRunnersSessionRunnerId` operationId).
func (c *Client) GetSessionRunnersSessionRunnerId(ctx context.Context, sessionRunnerId Ulid, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetSessionRunnersSessionRunnerIdRequest(c.Server, sessionRunnerId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostSessionRunnersSessionRunnerIdContactWithBody Contact endpoint for session runners
//
// TODO.
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /session_runners/{session_runner_id}/contact (the `PostSessionRunnersSessionRunnerIdContact` operationId).
func (c *Client) PostSessionRunnersSessionRunnerIdContactWithBody(ctx context.Context, sessionRunnerId Ulid, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostSessionRunnersSessionRunnerIdContactRequestWithBody(c.Server, sessionRunnerId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostSessionRunnersSessionRunnerIdContact Contact endpoint for session runners
//
// TODO.
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /session_runners/{session_runner_id}/contact (the `PostSessionRunnersSessionRunnerIdContact` operationId).
func (c *Client) PostSessionRunnersSessionRunnerIdContact(ctx context.Context, sessionRunnerId Ulid, body PostSessionRunnersSessionRunnerIdContactJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostSessionRunnersSessionRunnerIdContactRequest(c.Server, sessionRunnerId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPostSessionRunnersRequest calls the generic PostSessionRunners builder with application/json body
func NewPostSessionRunnersRequest(server string, body PostSessionRunnersJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostSessionRunnersRequestWithBody(server, "application/json", bodyReader)
}

// NewPostSessionRunnersRequestWithBody constructs an http.Request for the PostSessionRunners method, with any body, and a specified content type
func NewPostSessionRunnersRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/session_runners")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostSessionRunnersRegisterRequest calls the generic PostSessionRunnersRegister builder with application/json body
func NewPostSessionRunnersRegisterRequest(server string, body PostSessionRunnersRegisterJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostSessionRunnersRegisterRequestWithBody(server, "application/json", bodyReader)
}

// NewPostSessionRunnersRegisterRequestWithBody constructs an http.Request for the PostSessionRunnersRegister method, with any body, and a specified content type
func NewPostSessionRunnersRegisterRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/session_runners/register")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetSessionRunnersSessionRunnerIdRequest constructs an http.Request for the GetSessionRunnersSessionRunnerId method
func NewGetSessionRunnersSessionRunnerIdRequest(server string, sessionRunnerId Ulid) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "session_runner_id", sessionRunnerId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/session_runners/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostSessionRunnersSessionRunnerIdContactRequest calls the generic PostSessionRunnersSessionRunnerIdContact builder with application/json body
func NewPostSessionRunnersSessionRunnerIdContactRequest(server string, sessionRunnerId Ulid, body PostSessionRunnersSessionRunnerIdContactJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostSessionRunnersSessionRunnerIdContactRequestWithBody(server, sessionRunnerId, "application/json", bodyReader)
}

// NewPostSessionRunnersSessionRunnerIdContactRequestWithBody constructs an http.Request for the PostSessionRunnersSessionRunnerIdContact method, with any body, and a specified content type
func NewPostSessionRunnersSessionRunnerIdContactRequestWithBody(server string, sessionRunnerId Ulid, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "session_runner_id", sessionRunnerId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/session_runners/%s/contact", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// PostSessionRunnersWithBodyWithResponse Create a new session runner
	//
	// TODO.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /session_runners (the `PostSessionRunners` operationId).
	PostSessionRunnersWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostSessionRunnersResponse, error)

	// PostSessionRunnersWithResponse Create a new session runner
	//
	// TODO.
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /session_runners (the `PostSessionRunners` operationId).
	PostSessionRunnersWithResponse(ctx context.Context, body PostSessionRunnersJSONRequestBody, reqEditors ...RequestEditorFn) (*PostSessionRunnersResponse, error)

	// PostSessionRunnersRegisterWithBodyWithResponse Register a session runner
	//
	// TODO.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /session_runners/register (the `PostSessionRunnersRegister` operationId).
	PostSessionRunnersRegisterWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostSessionRunnersRegisterResponse, error)

	// PostSessionRunnersRegisterWithResponse Register a session runner
	//
	// TODO.
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /session_runners/register (the `PostSessionRunnersRegister` operationId).
	PostSessionRunnersRegisterWithResponse(ctx context.Context, body PostSessionRunnersRegisterJSONRequestBody, reqEditors ...RequestEditorFn) (*PostSessionRunnersRegisterResponse, error)

	// GetSessionRunnersSessionRunnerIdWithResponse Get a session runner
	//
	// TODO.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /session_runners/{session_runner_id} (the `GetSessionRunnersSessionRunnerId` operationId).
	GetSessionRunnersSessionRunnerIdWithResponse(ctx context.Context, sessionRunnerId Ulid, reqEditors ...RequestEditorFn) (*GetSessionRunnersSessionRunnerIdResponse, error)

	// PostSessionRunnersSessionRunnerIdContactWithBodyWithResponse Contact endpoint for session runners
	//
	// TODO.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /session_runners/{session_runner_id}/contact (the `PostSessionRunnersSessionRunnerIdContact` operationId).
	PostSessionRunnersSessionRunnerIdContactWithBodyWithResponse(ctx context.Context, sessionRunnerId Ulid, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostSessionRunnersSessionRunnerIdContactResponse, error)

	// PostSessionRunnersSessionRunnerIdContactWithResponse Contact endpoint for session runners
	//
	// TODO.
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /session_runners/{session_runner_id}/contact (the `PostSessionRunnersSessionRunnerIdContact` operationId).
	PostSessionRunnersSessionRunnerIdContactWithResponse(ctx context.Context, sessionRunnerId Ulid, body PostSessionRunnersSessionRunnerIdContactJSONRequestBody, reqEditors ...RequestEditorFn) (*PostSessionRunnersSessionRunnerIdContactResponse, error)
}

type PostSessionRunnersResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON201 the response for an HTTP 201 `application/json` response
	JSON201 *SessionRunner
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *Error
}

// GetJSON201 returns the response for an HTTP 201 `application/json` response
func (r PostSessionRunnersResponse) GetJSON201() *SessionRunner {
	return r.JSON201
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r PostSessionRunnersResponse) GetJSONDefault() *Error {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r PostSessionRunnersResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r PostSessionRunnersResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostSessionRunnersResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostSessionRunnersResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PostSessionRunnersRegisterResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *SessionRunnerRegisterResponse
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r PostSessionRunnersRegisterResponse) GetJSON200() *SessionRunnerRegisterResponse {
	return r.JSON200
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r PostSessionRunnersRegisterResponse) GetJSONDefault() *Error {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r PostSessionRunnersRegisterResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r PostSessionRunnersRegisterResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostSessionRunnersRegisterResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostSessionRunnersRegisterResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetSessionRunnersSessionRunnerIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *SessionRunner
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *ErrorResponse
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetSessionRunnersSessionRunnerIdResponse) GetJSON200() *SessionRunner {
	return r.JSON200
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r GetSessionRunnersSessionRunnerIdResponse) GetJSON404() *ErrorResponse {
	return r.JSON404
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r GetSessionRunnersSessionRunnerIdResponse) GetJSONDefault() *Error {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r GetSessionRunnersSessionRunnerIdResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetSessionRunnersSessionRunnerIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetSessionRunnersSessionRunnerIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetSessionRunnersSessionRunnerIdResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PostSessionRunnersSessionRunnerIdContactResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *SessionRunnerContactResponse
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r PostSessionRunnersSessionRunnerIdContactResponse) GetJSON200() *SessionRunnerContactResponse {
	return r.JSON200
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r PostSessionRunnersSessionRunnerIdContactResponse) GetJSONDefault() *Error {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r PostSessionRunnersSessionRunnerIdContactResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r PostSessionRunnersSessionRunnerIdContactResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostSessionRunnersSessionRunnerIdContactResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostSessionRunnersSessionRunnerIdContactResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// PostSessionRunnersWithBodyWithResponse Create a new session runner
//
// TODO.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /session_runners (the `PostSessionRunners` operationId).
func (c *ClientWithResponses) PostSessionRunnersWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostSessionRunnersResponse, error) {
	rsp, err := c.PostSessionRunnersWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostSessionRunnersResponse(rsp)
}

// PostSessionRunnersWithResponse Create a new session runner
//
// TODO.
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /session_runners (the `PostSessionRunners` operationId).
func (c *ClientWithResponses) PostSessionRunnersWithResponse(ctx context.Context, body PostSessionRunnersJSONRequestBody, reqEditors ...RequestEditorFn) (*PostSessionRunnersResponse, error) {
	rsp, err := c.PostSessionRunners(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostSessionRunnersResponse(rsp)
}

// PostSessionRunnersRegisterWithBodyWithResponse Register a session runner
//
// TODO.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /session_runners/register (the `PostSessionRunnersRegister` operationId).
func (c *ClientWithResponses) PostSessionRunnersRegisterWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostSessionRunnersRegisterResponse, error) {
	rsp, err := c.PostSessionRunnersRegisterWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostSessionRunnersRegisterResponse(rsp)
}

// PostSessionRunnersRegisterWithResponse Register a session runner
//
// TODO.
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /session_runners/register (the `PostSessionRunnersRegister` operationId).
func (c *ClientWithResponses) PostSessionRunnersRegisterWithResponse(ctx context.Context, body PostSessionRunnersRegisterJSONRequestBody, reqEditors ...RequestEditorFn) (*PostSessionRunnersRegisterResponse, error) {
	rsp, err := c.PostSessionRunnersRegister(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostSessionRunnersRegisterResponse(rsp)
}

// GetSessionRunnersSessionRunnerIdWithResponse Get a session runner
//
// TODO.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /session_runners/{session_runner_id} (the `GetSessionRunnersSessionRunnerId` operationId).
func (c *ClientWithResponses) GetSessionRunnersSessionRunnerIdWithResponse(ctx context.Context, sessionRunnerId Ulid, reqEditors ...RequestEditorFn) (*GetSessionRunnersSessionRunnerIdResponse, error) {
	rsp, err := c.GetSessionRunnersSessionRunnerId(ctx, sessionRunnerId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetSessionRunnersSessionRunnerIdResponse(rsp)
}

// PostSessionRunnersSessionRunnerIdContactWithBodyWithResponse Contact endpoint for session runners
//
// TODO.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /session_runners/{session_runner_id}/contact (the `PostSessionRunnersSessionRunnerIdContact` operationId).
func (c *ClientWithResponses) PostSessionRunnersSessionRunnerIdContactWithBodyWithResponse(ctx context.Context, sessionRunnerId Ulid, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostSessionRunnersSessionRunnerIdContactResponse, error) {
	rsp, err := c.PostSessionRunnersSessionRunnerIdContactWithBody(ctx, sessionRunnerId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostSessionRunnersSessionRunnerIdContactResponse(rsp)
}

// PostSessionRunnersSessionRunnerIdContactWithResponse Contact endpoint for session runners
//
// TODO.
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /session_runners/{session_runner_id}/contact (the `PostSessionRunnersSessionRunnerIdContact` operationId).
func (c *ClientWithResponses) PostSessionRunnersSessionRunnerIdContactWithResponse(ctx context.Context, sessionRunnerId Ulid, body PostSessionRunnersSessionRunnerIdContactJSONRequestBody, reqEditors ...RequestEditorFn) (*PostSessionRunnersSessionRunnerIdContactResponse, error) {
	rsp, err := c.PostSessionRunnersSessionRunnerIdContact(ctx, sessionRunnerId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostSessionRunnersSessionRunnerIdContactResponse(rsp)
}

// ParsePostSessionRunnersResponse parses an HTTP response from a PostSessionRunnersWithResponse call
func ParsePostSessionRunnersResponse(rsp *http.Response) (*PostSessionRunnersResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostSessionRunnersResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest SessionRunner
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParsePostSessionRunnersRegisterResponse parses an HTTP response from a PostSessionRunnersRegisterWithResponse call
func ParsePostSessionRunnersRegisterResponse(rsp *http.Response) (*PostSessionRunnersRegisterResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostSessionRunnersRegisterResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest SessionRunnerRegisterResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseGetSessionRunnersSessionRunnerIdResponse parses an HTTP response from a GetSessionRunnersSessionRunnerIdWithResponse call
func ParseGetSessionRunnersSessionRunnerIdResponse(rsp *http.Response) (*GetSessionRunnersSessionRunnerIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetSessionRunnersSessionRunnerIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest SessionRunner
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParsePostSessionRunnersSessionRunnerIdContactResponse parses an HTTP response from a PostSessionRunnersSessionRunnerIdContactWithResponse call
func ParsePostSessionRunnersSessionRunnerIdContactResponse(rsp *http.Response) (*PostSessionRunnersSessionRunnerIdContactResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostSessionRunnersSessionRunnerIdContactResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest SessionRunnerContactResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"xFhbc9s2E/0rGHx5pC3ZsZLPenPiTuo2aTx20oc6qgYiVhRiEmCxS1mqR/+9A4C68GJLvsR5k0jsYnfP",
	"wdkFb3lsstxo0IS8f8stYG40gv/zi7XGuh+x0QSa3E+R56mKBSmjO9/RaPcM4wlkwv16ZWHM+/x/nbXX",
	"TniLHe/tovTPF4tFxCVgbFXunPE+/zIBFhazsbFMpCk7ms2Y0JL1ZjO2Ds2Zll5XYa4c9295bk0OllTI",
	"ApZZVB/HRvrFMBNZngLvHxx1jyIOszgtUE3hk9IqKzLeJ1tAxLPl327EaZ4D73OlCRKw3CdCQqUVd/yE",
	"ZcYCC69AMuPzFCnLAFEkwHBibpRO2M1EEKMJsNyaUQoZuxHIV7sgWaUTt0lpV93l0mRAE+8GNLEba3TC",
	"9liegkBgZOdMJEJplgoC2+aVrIhhqKRzW8XjErSz9wvY2akHJVX62m1GhsXGBkike5CahLn1rrrRRnwi",
	"Pn593OvCMRwcHIleL37zdjz6P/Rg3Ds4Ho2gGdIi4hb+KZQFyftXAad18oPVejP6DjE11ge4m8sifgmI",
	"yuiLQmvwhBBSqoDJ+QY1xiJFqHPzhGGwZjaYRzU6hQLex/+vqZLcB5soJOuP0JDMNfgz1MDFAprCxjDM",
	"jUlLfJrEQxJU4LatK5lfBpN63ZTkLZuudtha0BNElWiQ5cPWnO4zwCYBnSCkComZ8bL8yERp5igo1mgo",
	"guxhdagHvFhlKKwV80a8740mEdO5QXogeU4FCYb+eE5AM1HjEouDZ/QicHJ+1iDXGmXQToOuuAUh5zzi",
	"2tAw/B5sO0i7AlnmuSmoj8p1JOLrRye8wYnHAhoofn+ujwVzWVevgxYEQSPJRk67HOgaZA2TreBdeHF5",
	"nsRs6WuX1HaQtEZuDZuds3skN52eWMAi9YqyTM91r60ZioImd+8WRoSaRRwD4roa65aIJoNh5XVLW4ZZ",
	"rizgUFWN33Rb5w8LYws4Gd5h9XqL2V1BVt+3RImxyWsDichV65jhXAzD483l70DYtsGkxpZ6udbeKqWq",
	"p9TGKLvq/zsrS5O8S5Z4Xmzl7eVKv1smXv/OEbKFhEu51zAFOyxlE1xbVlqREqn611Ur2qkfRNyPII0o",
	"vn48O2VKgiY1Vn7bTMw+gk4c5Q/f+Nl3828uiMA6y7+vuntvB1fdveOTvV9/+/3TH+d7X/7c+2twe9hb",
	"vGrBdOHiHpu2QihkCHaqYmAq9IXMja2uiYCWfva8AH1d7LMzcoPyVElA5rzZzGsIEyNTECsQLEZuhUMC",
	"o286Tk0hGZKxIoGIBSaFATbLC/KS4FUW/VUjE3rODE3AMj9X4/43zzhFnq8+COa18jLEi2UHm4INgw+f",
	"Hrhimxy0Owx9/nq/u3/IfeEmngWdEuhhANo/y0vFrhXm8+ln7n0FpTyTvM+duFf4hTzQE5DeGTl/titb",
	"s1cuqifBCV+YVde3xsPuwY8J4M47Y3W4uBFY9mQZrmZjUaR0106r0MP9NNwtiywTds77/P2yt2u4aZ5O",
	"Egn6yaqG5sA5qWPcWfabJ4O97IIvAXplntgJ/O6PDWTrB4QmGZaFfwY+XNwzEj2MDbfVB0MlFy6kBHbl",
	"xQeo0aLy76y8zb0AMrsh4Up/1D164a9JVTJIA8i0IQYzhfRkMnwAehgPXAewIgPykn91y92Y5ruC69wi",
	"872yTgteP3LRjhUK3xsWgx3Z1ymnCy9PPyHM6GmiWGN/eYl9CYnc/C7wMxWyfm+/40xIQH/Bc3MnuLGT",
	"Ws/q09pmCIWBlrlRmvz4Vt0D71dM5w7sdMnAwqa8zzsiVx0pSPDFYPFfAAAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
