dependencies:
- name: renku-core
  alias: core
  repository: "https://swissdatasciencecenter.github.io/helm-charts/"
  version: 0.16.2
- name: renku-ui
  alias: ui
  repository: "https://swissdatasciencecenter.github.io/helm-charts/"
  version: 1.0.2
- name: renku-ui-server
  alias: uiserver
  repository: "https://swissdatasciencecenter.github.io/helm-charts/"
  version: 1.0.2
- name: renku-notebooks
  alias: notebooks
  repository: "https://swissdatasciencecenter.github.io/helm-charts/"
  version: 1.2.0
- name: renku-gateway
  alias: gateway
  repository: "https://swissdatasciencecenter.github.io/helm-charts/"
  version: 0.10.1
- name: gitlab
  repository: "https://swissdatasciencecenter.github.io/helm-charts/"
  version: 0.6.0
  condition: gitlab.enabled
- name: renku-graph
  alias: graph
  repository: "https://swissdatasciencecenter.github.io/helm-charts/"
  version: 1.37.5
  condition: graph.enabled
- name: postgresql
  version: 9.1.1
  repository: "https://charts.bitnami.com/bitnami"
  condition: postgresql.enabled
- name: keycloak
  version: 9.8.1
  repository: "https://codecentric.github.io/helm-charts"
  condition: keycloak.enabled
