dependencies:
  - name: postgresql
    version: "14.2.4"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    condition: postgresql.enabled
  - name: keycloakx
    version: 2.1.0
    repository: "https://codecentric.github.io/helm-charts"
    condition: keycloakx.enabled
  - name: redis
    repository: "oci://registry-1.docker.io/bitnamicharts"
    version: 20.3.0
    condition: redis.install
  - name: renku-jena
    version: "0.0.25"
    repository: "https://swissdatasciencecenter.github.io/helm-charts/"
    alias: jena
  - name: amalthea
    repository: "https://swissdatasciencecenter.github.io/helm-charts/"
    version: "0.18.1"
  - name: amalthea-sessions
    repository: "https://swissdatasciencecenter.github.io/helm-charts/"
    version: "0.18.1"
  - name: dlf-chart
    repository: "https://swissdatasciencecenter.github.io/datashim/"
    version: "0.3.9-renku-2"
    condition: notebooks.cloudstorage.s3.installDatashim
  - name: csi-rclone
    repository: "https://swissdatasciencecenter.github.io/helm-charts/"
    version: "0.3.7"
    condition: global.csi-rclone.install
  - name: solr
    repository: "oci://registry-1.docker.io/bitnamicharts"
    version: "8.9.2"
    condition: solr.enabled
    # setting the version of bitnami-common here to avoid conflicts in sub-charts bundling different versions
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - bitnami-common
    version: 2.x.x
