dependencies:
- name: renku-core
  alias: core
  repository: "https://swissdatasciencecenter.github.io/helm-charts/"
  version: 1.3.1
- name: renku-ui
  alias: ui
  repository: "https://swissdatasciencecenter.github.io/helm-charts/"
  version: 2.3.1
- name: renku-ui-server
  alias: uiserver
  repository: "https://swissdatasciencecenter.github.io/helm-charts/"
  version: 2.3.2
- name: renku-notebooks
  alias: notebooks
  repository: "https://swissdatasciencecenter.github.io/helm-charts/"
  version: 1.7.0
- name: renku-gateway
  alias: gateway
  repository: "https://swissdatasciencecenter.github.io/helm-charts/"
  version: 0.13.1
- name: gitlab
  repository: "https://swissdatasciencecenter.github.io/helm-charts/"
  version: 0.6.0
  condition: gitlab.enabled
- name: renku-graph
  alias: graph
  repository: "https://swissdatasciencecenter.github.io/helm-charts/"
  version: 2.8.1
  condition: graph.enabled
- name: postgresql
  version: 9.1.1
  repository: "https://raw.githubusercontent.com/bitnami/charts/eb5f9a9513d987b519f0ecd732e7031241c50328/bitnami"
  condition: postgresql.enabled
- name: keycloak
  version: 16.0.4
  repository: "https://codecentric.github.io/helm-charts"
  condition: keycloak.enabled
- name: certificates
  version: 0.0.2
  repository: "https://swissdatasciencecenter.github.io/helm-charts/"
- name: redis
  version: 10.7.11
  repository: "https://raw.githubusercontent.com/bitnami/charts/eb5f9a9513d987b519f0ecd732e7031241c50328/bitnami"
  condition: redis.install
