dependencies:
- name: renku-core
  alias: core
  repository: "https://swissdatasciencecenter.github.io/helm-charts/"
  version: 0.16.0
- name: renku-ui
  alias: ui
  repository: "https://swissdatasciencecenter.github.io/helm-charts/"
  version: 0.11.14
- name: renku-ui-server
  alias: uiserver
  repository: "https://swissdatasciencecenter.github.io/helm-charts/"
  version: 0.11.14
- name: renku-notebooks
  alias: notebooks
  repository: "https://swissdatasciencecenter.github.io/helm-charts/"
  version: 0.8.13
- name: renku-gateway
  alias: gateway
  repository: "https://swissdatasciencecenter.github.io/helm-charts/"
  version: 0.9.4
- name: gitlab
  repository: "https://swissdatasciencecenter.github.io/helm-charts/"
  version: 0.5.2
  condition: gitlab.enabled
- name: renku-graph
  alias: graph
  repository: "https://swissdatasciencecenter.github.io/helm-charts/"
  version: 1.36.6
  condition: graph.enabled
- name: postgresql
  version: 9.1.1
  repository: "https://charts.bitnami.com/bitnami"
  condition: postgresql.enabled
- name: keycloak
  version: 9.8.1
  repository: "https://codecentric.github.io/helm-charts"
  condition: keycloak.enabled
