apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "renku.fullname" . }}-gateway-revproxy
  labels:
    app: {{ template "gateway.name" . }}-revproxy
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  config.yaml: |
    server:
      port: 8080
      host: 0.0.0.0
      rateLimits:
        enabled: {{ .Values.gateway.rateLimits.general.enabled }}
        rate: {{ .Values.gateway.rateLimits.general.average }}
        burst: {{ .Values.gateway.rateLimits.general.burst }}
    revproxy:
      renkuBaseUrl: {{ include "renku.baseUrl" . | quote }}
      {{- if .Values.gitlab.enabled }}
      externalGitlabUrl: ""
      {{- else }}
      externalGitlabUrl: {{ .Values.global.gitlab.url | default "" | quote }}
      {{- end }}
      k8sNamespace: {{ .Release.Namespace }}
      renkuServices:
        gatewayAuth: {{ printf "http://%s-gateway-auth" .Release.Name | quote }}
        notebooks: {{ printf "http://%s-notebooks" .Release.Name | quote }}
        kg: {{ printf "http://%s-knowledge-graph" .Release.Name | quote }}
        webhook: {{ printf "http://%s-webhook-service" .Release.Name | quote }}
        core:
          serviceNames: 
            {{- include "gateway.core.serviceNamesYaml" . | nindent 12 }}
          servicePaths: 
            {{- include "gateway.core.pathsYaml" . | nindent 12 }}
          sticky: true 
        dataService: {{ printf "http://%s-data-service" .Release.Name | quote }}
        keycloak: {{ include "renku.keycloakUrl" . | quote }} 
        search: {{ printf "http://%s-search-api" .Release.Name | quote }}
        uiserver: {{ printf "http://%s" (include "ui-server.fullname" .) | quote }}
    redis:
      type: redis
      addresses:
        - {{ printf "%s:%d" .Values.global.redis.host (.Values.global.redis.port | int) | quote }}
      isSentinel: {{ .Values.global.redis.sentinel.enabled }}
      masterName: {{ .Values.global.redis.sentinel.masterSet | quote }}
      dbIndex: {{ .Values.global.redis.dbIndex.gateway }}
    monitoring:
      sentry:
        enabled: {{ .Values.gateway.reverseProxy.sentry.enabled }}
        environment: {{ .Values.gateway.reverseProxy.sentry.environment }}
        sampleRate: {{ .Values.gateway.reverseProxy.sentry.sampleRate }}
      prometheus:
        enabled: {{ .Values.gateway.reverseProxy.metrics.enabled }}
        port: {{ .Values.gateway.reverseProxy.metrics.port }}
---

