apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "renku.fullname" . }}-gateway-revproxy
  labels:
    app: {{ template "gateway.name" . }}-revproxy
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  {{- if not .Values.gateway.reverseProxy.autoscaling.enabled }}
  replicas: {{ .Values.gateway.reverseProxy.replicaCount }}
  {{- end }}
  strategy:
    {{- toYaml .Values.gateway.reverseProxy.updateStrategy | nindent 4 }}
  selector:
    matchLabels:
      app: {{ template "gateway.name" . }}-revproxy
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "gateway.name" . }}-revproxy
        release: {{ .Release.Name }}
      {{- with .Values.gateway.reverseProxy.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: "{{ template "renku.fullname" . }}-gateway-revproxy"
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        {{- include "certificates.initContainer" . | nindent 8 }}
      containers:
        - name: revproxy
          image: "{{ .Values.gateway.reverseProxy.image.repository }}:{{ .Values.gateway.reverseProxy.image.tag }}"
          imagePullPolicy: {{ .Values.gateway.reverseProxy.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: GATEWAY_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.redis.existingSecret }}
                  key: {{ .Values.global.redis.existingSecretPasswordKey }}
            - name: GATEWAY_MONITORING_SENTRY_DSN
              value: {{ .Values.gateway.sentry.dsn }}
          volumeMounts:
            {{- include "certificates.volumeMounts.system" . | nindent 12 }}
            - mountPath: "/etc/gateway"
              name: public-config
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 2
            failureThreshold: 2
          resources:
            {{ toYaml .Values.gateway.reverseProxy.resources | nindent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{ toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        {{- include "certificates.volumes" . | nindent 8 }}
        - name: public-config
          configMap:
            name: {{ template "renku.fullname" . }}-gateway-revproxy
