apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "renku.fullname" . }}-gateway
  labels:
    app: {{ template "gateway.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  {{- if not .Values.gateway.autoscaling.enabled }}
  replicas: {{ .Values.gateway.replicaCount }}
  {{- end }}
  strategy:
    {{- toYaml .Values.gateway.updateStrategy | nindent 4 }}
  selector:
    matchLabels:
      app: {{ template "gateway.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "gateway.name" . }}
        release: {{ .Release.Name }}
        # The label below enables the gateway to connect to redis
        {{ .Values.global.redis.clientLabel | toYaml | nindent 8 }}
      {{- if .Values.gateway.podAnnotations }}
      {{- with .Values.gateway.podAnnotations }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/gateway/configmap.yaml") . | sha256sum }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- else }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/gateway/configmap.yaml") . | sha256sum }}
      {{- end }}
    spec:
      serviceAccountName: "{{ template "renku.fullname" . }}-gateway"
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        {{- include "certificates.initContainer" . | nindent 8 }}
      containers:
        - name: gateway
          image: "{{ .Values.gateway.image.repository }}:{{ .Values.gateway.image.tag }}"
          imagePullPolicy: {{ .Values.gateway.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: GATEWAY_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.redis.existingSecret }}
                  key: {{ .Values.global.redis.existingSecretPasswordKey }}
            - name: GATEWAY_SESSIONS_COOKIEENCODINGKEY
              valueFrom:
                secretKeyRef:
                  name: {{ cat (include "renku.fullname" .) "-gateway" | nospace }}
                  key: cookieEncodingKey
            - name: GATEWAY_SESSIONS_COOKIEHASHKEY
              valueFrom:
                secretKeyRef:
                  name: {{ cat (include "renku.fullname" .) "-gateway" | nospace }}
                  key: cookieHashKey
            - name: GATEWAY_LOGIN_PROVIDERS_RENKU_CLIENTSECRET
              valueFrom:
                secretKeyRef:
                  name: {{ cat (include "renku.fullname" .) "-gateway" | nospace }}
                  key: oidcClientSecret
            {{- if .Values.enableV1Services }}
            - name: GATEWAY_LOGIN_PROVIDERS_GITLAB_CLIENTSECRET
              valueFrom:
                secretKeyRef:
                  name: {{ cat (include "renku.fullname" .) "-gateway" | nospace }}
                  key: gitlabClientSecret
            {{- end }}
            - name: GATEWAY_LOGIN_TOKENENCRYPTION_SECRETKEY
              valueFrom:
                secretKeyRef:
                  name: {{ cat (include "renku.fullname" .) "-gateway" | nospace }}
                  key: tokenEncryption
            - name: GATEWAY_LOGIN_PROVIDERS_RENKU_COOKIEENCODINGKEY
              valueFrom:
                secretKeyRef:
                  name: {{ cat (include "renku.fullname" .) "-gateway" | nospace }}
                  key: cookieEncodingKey
            - name: GATEWAY_LOGIN_PROVIDERS_RENKU_COOKIEHASHKEY
              valueFrom:
                secretKeyRef:
                  name: {{ cat (include "renku.fullname" .) "-gateway" | nospace }}
                  key: cookieHashKey
            {{- if .Values.enableV1Services }}
            - name: GATEWAY_LOGIN_PROVIDERS_GITLAB_COOKIEENCODINGKEY
              valueFrom:
                secretKeyRef:
                  name: {{ cat (include "renku.fullname" .) "-gateway" | nospace }}
                  key: cookieEncodingKey
            - name: GATEWAY_LOGIN_PROVIDERS_GITLAB_COOKIEHASHKEY
              valueFrom:
                secretKeyRef:
                  name: {{ cat (include "renku.fullname" .) "-gateway" | nospace }}
                  key: cookieHashKey
            {{- end }}
            - name: GATEWAY_MONITORING_SENTRY_DSN
              value: {{ .Values.gateway.sentry.dsn }}
            - name: GATEWAY_POSTHOG_ENABLED
              value: {{ .Values.posthog.enabled | quote }}
            - name: GATEWAY_POSTHOG_APIKEY
              value: {{ .Values.posthog.apiKey | default "" | quote }}
            - name: GATEWAY_POSTHOG_HOST
              value: {{ .Values.posthog.host| default "" | quote }}
            - name: GATEWAY_POSTHOG_ENVIRONMENT
              value: {{ .Values.posthog.environment| default "" | quote }}
          volumeMounts:
            {{- include "certificates.volumeMounts.system" . | nindent 12 }}
            - mountPath: "/etc/gateway"
              name: public-config
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 2
            failureThreshold: 2
          resources:
            {{ toYaml .Values.gateway.resources | nindent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{ toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        {{- include "certificates.volumes" . | nindent 8 }}
        - name: public-config
          configMap:
            name: {{ template "renku.fullname" . }}-gateway
