apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "renku.fullname" . }}-gateway-auth
  labels:
    app: {{ template "gateway.name" . }}-auth
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "gateway.name" . }}-auth
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "gateway.name" . }}-auth
        release: {{ .Release.Name }}
        # The label below enables the gateway to connect to redis
        {{ .Values.global.redis.clientLabel | toYaml | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      automountServiceAccountToken: {{ .Values.global.debug }}
      initContainers:
        {{- include "certificates.initContainer" . | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.gateway.image.auth.repository }}:{{ .Values.gateway.image.auth.tag }}"
          imagePullPolicy: {{ .Values.gateway.image.auth.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          env:
            - name: HOST_NAME
              value: {{ include "renku.baseUrl" . | quote }}
            - name: CLI_CLIENT_ID
              value: "renku-cli"
            - name: CLI_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ cat (include "renku.fullname" .) "-gateway-revproxy" | nospace }}
                  key: cliClientSecret
            - name: GITLAB_URL
              value: {{ include "renku.gitlabUrl" . | quote }}
            - name: GITLAB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ cat (include "renku.fullname" .) "-gateway-revproxy" | nospace }}
                  key: gitlabClientSecret
            - name: GITLAB_CLIENT_ID
              value: {{ .Values.gateway.gitlabClientId | default .Values.global.gateway.gitlabClientId | quote }}
            - name: KEYCLOAK_URL
              value: {{ include "renku.keycloakUrl" . | quote }}
            - name: KEYCLOAK_REALM
              value: {{ include "renku.keycloak.realm" . | quote }}
            - name: GATEWAY_SERVICE_PREFIX
              value: "/api/"
            - name: REDIS_HOST
              value: {{ .Values.global.redis.host | quote }}
            - name: REDIS_IS_SENTINEL
              value: {{ .Values.global.redis.sentinel.enabled | quote }}
            - name: REDIS_MASTER_SET
              value: {{ .Values.global.redis.sentinel.masterSet | quote }}
            - name: REDIS_DB
              value: {{ .Values.global.redis.dbIndex.gateway | quote }}
            - name: REDIS_PORT
              value: {{ .Values.global.redis.port | quote }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.redis.existingSecret }}
                  key: {{ .Values.global.redis.existingSecretPasswordKey }}
            - name: GATEWAY_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ cat (include "renku.fullname" .) "-gateway-revproxy" | nospace }}
                  key: gatewaySecret
            - name: GATEWAY_ALLOW_ORIGIN
              value: {{ .Values.gateway.allowOrigin | quote }}
            - name: OIDC_CLIENT_ID
              value: {{ "renku" | quote }}
            - name: OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ cat (include "renku.fullname" .) "-gateway-revproxy" | nospace }}
                  key: oidcClientSecret
            - name: OLD_GITLAB_LOGOUT
              value: {{ .Values.gateway.oldGitLabLogout | quote }}
            - name: LOGOUT_GITLAB_UPON_RENKU_LOGOUT
              value: {{ .Values.gateway.logoutGitLabUponRenkuLogout | quote }}
            - name: WEBHOOK_SERVICE_HOSTNAME
              value: {{ printf "http://%s-graph-webhook-service" .Release.Name | quote }}
            {{ if .Values.global.anonymousSessions.enabled }}
            - name: ANONYMOUS_SESSIONS_ENABLED
              value: "true"
            {{ end }}
            # Note that this is ok because we're enforcing HTTPS
            # further up the processing chain.
            - name: OAUTHLIB_INSECURE_TRANSPORT
              value: "1"
            - name: SENTRY_ENABLED
              value: {{ .Values.gateway.sentry.enabled | quote }}
            - name: SENTRY_DSN
              value: {{ .Values.gateway.sentry.dsn }}
            - name: SENTRY_ENVIRONMENT
              value: {{ .Values.gateway.sentry.environment }}
            - name: SENTRY_SAMPLE_RATE
              value: {{ .Values.gateway.sentry.sampleRate | quote }}
            - name: DEBUG
              value: {{ .Values.global.debug | quote }}
            {{- include "certificates.env.python" . | nindent 12 }}
          volumeMounts:
            {{- include "certificates.volumeMounts.system" . | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 2
            failureThreshold: 2
          resources:
            {{ toYaml .Values.gateway.resources | nindent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{ toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        {{- include "certificates.volumes" . | nindent 8 }}
