{{- if or (gt (int .Values.gateway.replicaCount) 1) (and .Values.gateway.autoscaling.enabled (gt (int .Values.gateway.autoscaling.minReplicas) 1)) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ template "renku.fullname" . }}-gateway
  labels:
    app.kubernetes.io/name: {{ template "renku.name" . }}-gateway
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: gateway
    app.kubernetes.io/part-of: renku
    chart: {{ template "renku.chart" . }}
    heritage: {{ .Release.Service }}
spec:
  maxUnavailable: 50%
  selector:
    matchLabels:
      app: {{ template "renku.name" . }}-gateway
      release: {{ .Release.Name }}
{{- end }}

