apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "renku.fullname" . }}-gateway-revproxy
  labels:
    app: {{ template "renku.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "renku.fullname" . }}-gateway-revproxy
subjects:
  - kind: ServiceAccount
    name: {{ template "renku.fullname" . }}-gateway-revproxy
    namespace: {{ .Release.Namespace }}
