apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "renku.fullname" . }}-gateway
  labels:
    app.kubernetes.io/name: {{ template "renku.name" . }}
    {{- include "gateway.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "renku.fullname" . }}-gateway
subjects:
  - kind: ServiceAccount
    name: {{ template "renku.fullname" . }}-gateway
    namespace: {{ .Release.Namespace }}
