---

{{- $oidcClientSecret := .Values.gateway.oidcClientSecret | default .Values.global.gateway.clientSecret | default (randAlphaNum 64) | b64enc | quote }}
{{- $gitlabClientSecret := "" -}}
{{- if .Values.gitlab.enabled -}}
{{- $gitlabClientSecret = .Values.gateway.gitlabClientSecret | default .Values.global.gateway.gitlabClientSecret | default (randAlphaNum 64) | b64enc | quote }}
{{- else -}}
{{- $gitlabClientSecret = required "Fill in .Values.gateway.gitlabClientSecret or .Values.global.gateway.gitlabClientSecret with the OIDC client secret you created in Gitlab" (.Values.gateway.gitlabClientSecret | default .Values.global.gateway.gitlabClientSecret) | b64enc | quote -}}
{{- end -}}
{{- $gatewaySecret := .Values.gateway.secretKey | default (randAlphaNum 64) | b64enc | quote }}
{{- $cliClientSecret := .Values.gateway.cliClientSecret | default .Values.global.gateway.cliClientSecret | default (randAlphaNum 64) | b64enc | quote }}
{{- $notebooksClientSecret := .Values.notebooks.oidc.clientSecret | default (randAlphaNum 64) | b64enc | quote }}
{{- $uiserverClientSecret := .Values.global.uiserver.clientSecret | default (randAlphaNum 64) | b64enc | quote }}
{{- $gitlabClientInKeycloakSecret := .Values.global.gitlab.clientSecret | default (randAlphaNum 64) | b64enc | quote }}

{{- $renkuFullname := include "renku.fullname" . -}}
{{- $secretName := cat $renkuFullname "-gateway" | nospace }}

{{- if not (or .Values.gateway.oidcClientSecret .Values.global.gateway.clientSecret) -}}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace $secretName) }}
{{- if $secret }}
{{- $oidcClientSecret = index $secret.data "oidcClientSecret" }}
{{- end -}}
{{- end -}}

{{- if not (or .Values.gateway.gitlabClientSecret .Values.global.gateway.gitlabClientSecret) -}}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace $secretName) }}
{{- if $secret }}
{{- $gitlabClientSecret = index $secret.data "gitlabClientSecret" }}
{{- end -}}
{{- end -}}

{{- if not .Values.gateway.secretKey -}}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace $secretName) }}
{{- if $secret }}
{{- $gatewaySecret = index $secret.data "gatewaySecret" }}
{{- end -}}
{{- end -}}

{{- if not (or .Values.gateway.cliClientSecret .Values.global.gateway.cliClientSecret) -}}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace $secretName) }}
{{- if $secret }}
{{- $cliClientSecret = index $secret.data "cliClientSecret" }}
{{- end -}}
{{- end -}}

{{- if not .Values.notebooks.oidc.clientSecret -}}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace $secretName) }}
{{- if $secret }}
{{- $notebooksClientSecret = index $secret.data "notebooksClientSecret" }}
{{- end -}}
{{- end -}}

{{- if not .Values.global.uiserver.clientSecret -}}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace $secretName) }}
{{- if $secret }}
{{- $uiserverClientSecret = index $secret.data "uiserverClientSecret" }}
{{- end -}}
{{- end -}}

{{- if .Values.gitlab.enabled -}}
{{- if not .Values.global.gitlab.clientSecret -}}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace $secretName) }}
{{- if $secret }}
{{- $gitlabClientInKeycloakSecret = index $secret.data "gitlabClientInKeycloakSecret" }}
{{- end -}}
{{- end -}}
{{- end }}

{{- $tokenEncryptionSecretKey := randAlphaNum 32 | b64enc | quote }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace $secretName) }}
{{- if $secret }}
{{- $tokenEncryptionSecretKey = index $secret.data "tokenEncryption" }}
{{- end -}}

{{- $csrfCookieEncodingKey := randAlphaNum 32 | b64enc | quote }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace $secretName) }}
{{- if $secret }}
{{- $csrfCookieEncodingKey = index $secret.data "cookieEncodingKey" }}
{{- end -}}

{{- $csrfCookieHashKey := randAlphaNum 32 | b64enc | quote }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace $secretName) }}
{{- if $secret }}
{{- $csrfCookieHashKey = index $secret.data "cookieHashKey" }}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    app: {{ template "renku.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade,pre-rollback"
type: Opaque
data:
  # A secret for the "renku" OIDC client in Keycloak
  oidcClientSecret: {{ $oidcClientSecret }}
  # A secret for the Renku OIDC client in Gitlab
  # If an external Gitlab is used the OIDC client must be created manually prior to installing Renku
  # If the Renku-bundled Gitlab is used then the OIDC client will be created in Gitlab automatically from the value of this secret
  gitlabClientSecret: {{ $gitlabClientSecret }}
  # A secret which must be exactly 64 hex characters, used to encrypt session cookies for the gateway and redis content
  gatewaySecret: {{ $gatewaySecret }}
  # A secret for the Renku CLI client in Keycloak
  cliClientSecret: {{ $cliClientSecret }}
  # A secret for the Renku notebooks client in Keycloak
  notebooksClientSecret: {{ $notebooksClientSecret }}
  # A secret for the UI server client in Keycloak
  uiserverClientSecret: {{ $uiserverClientSecret }}
  {{- if .Values.gitlab.enabled }}
  # A secret for the Gitlab client in Keycloak if an internal Gitlab is used
  gitlabClientInKeycloakSecret: {{ $gitlabClientInKeycloakSecret }}
  {{- end }}
  cookieEncodingKey: {{ $csrfCookieEncodingKey }}
  cookieHashKey: {{ $csrfCookieHashKey }}
  tokenEncryption: {{ $tokenEncryptionSecretKey }}

