---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "renku.fullname" . }}-gateway
  labels:
    app.kubernetes.io/name: {{ template "renku.name" . }}-gateway
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: gateway
    app.kubernetes.io/part-of: renku
    chart: {{ template "renku.chart" . }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.gateway.service.type }}
  ports:
    - port: {{ .Values.gateway.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ template "gateway.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
