apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "renku.fullname" . }}-gateway
  labels:
    app.kubernetes.io/name: {{ template "renku.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: gateway
    app.kubernetes.io/part-of: renku
    chart: {{ template "renku.chart" . }}
    heritage: {{ .Release.Service }}
