apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  # Allow egress to get to the dev machine
  name: allow-egress-to-own-machine
  labels:
    {{- include "netpol.labels" . | nindent 4 }}
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 172.29.21.238/32
        - ipBlock:
            cidr: 192.168.1.241/32
