apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-external
  labels:
    {{- include "netpol.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      renku.io/allow-external: "true"
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 10.0.0.0/8
              - 172.16.0.0/12
              - 192.168.0.0/16
              # Cloud instance metadata API
              - 169.254.169.254/32
