---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-to-authz
spec:
  policyTypes:
    - Ingress
  podSelector:
    matchLabels:
      app.kubernetes.io/name: renku-authz
  ingress:
    - from:
        - podSelector:
            matchLabels:
              renku.io/authz-access: "true"
      ports:
        - protocol: TCP
          port: http
        - protocol: TCP
          port: grpc
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-to-authz
spec:
  policyTypes:
    - Egress
  podSelector:
    matchLabels:
      renku.io/authz-access: "true"
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: renku-authz
      ports:
        - protocol: TCP
          port: http
        - protocol: TCP
          port: grpc
