{{- if not .Values.global.externalServices.postgresql.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-to-database
spec:
  policyTypes:
    - Ingress
  podSelector:
    matchLabels:
      app.kubernetes.io/name: postgresql
  ingress:
    - from:
        - podSelector:
            matchLabels:
              renku.io/database-access: "true"
      ports:
        - protocol: TCP
          port: 5432
        - protocol: TCP
          port: 9187
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-to-database
spec:
  policyTypes:
    - Egress
  podSelector:
    matchLabels:
      renku.io/database-access: "true"
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: postgresql
      ports:
        - protocol: TCP
          port: 5432
        - protocol: TCP
          port: 9187
{{- end }}
