---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-from-ingress-controller
spec:
  policyTypes:
    - Ingress
  podSelector:
    matchLabels:
      renku.io/ingress-access: "true"
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app.kubernetes.io/name: ingress-nginx
        namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: ingress-nginx
      ports:
        - protocol: TCP
          port: http
        - protocol: TCP
          port: https
