---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-to-secrets-storage
spec:
  policyTypes:
    - Ingress
  podSelector:
    matchLabels:
      app.kubernetes.io/name: renku-secrets-storage
  ingress:
    - from:
        - podSelector:
            matchLabels:
              renku.io/secrets-storage-access: "true"
      ports:
        - protocol: TCP
          port: http
        - protocol: TCP
          port: https
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: renku-secrets-storage
      ports:
        - protocol: TCP
          port: http
        - protocol: TCP
          port: https
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-to-secrets-storage
spec:
  policyTypes:
    - Egress
  podSelector:
    matchLabels:
      renku.io/secrets-storage-access: "true"
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: renku-secrets-storage
      ports:
        - protocol: TCP
          port: http
        - protocol: TCP
          port: https
