---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-from-sessions
  labels:
    {{- include "netpol.labels" . | nindent 4 }}
spec:
  podSelector:
    matchExpressions:
      - key: app.kubernetes.io/name
        operator: In
        values:
          - renku-data-service
          - keycloakx
          - {{ template "gateway.name" . }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/created-by: controller-manager
              app.kubernetes.io/name: AmaltheaSession
      ports:
        - protocol: TCP
          port: http
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: amalthea-sessions-v2
  labels:
    {{- include "netpol.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: AmaltheaSession
      app.kubernetes.io/part-of: amaltheasession-operator
  policyTypes:
    - Ingress
  ingress:
    - from:
      # Allow ingress to the authentication proxy port on a v2 session
      - podSelector:
          matchLabels:
            app.kubernetes.io/name: ingress-nginx
        namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: ingress-nginx
      ports:
        - protocol: TCP
          # This port is hardcoded in Amalthea as the port for the authentication proxy
          port: 65535
    - from:
      # Allow amalthea operator access to auth proxy metadata endpoint
      - podSelector:
          matchLabels:
            app.kubernetes.io/name: amalthea-sessions
      ports:
        - protocol: TCP
          # This port is hardcoded in Amalthea as the port for the authentication proxy metadata endpoint
          port: 65534

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: amalthea-sessions-v2-tunnel
  labels:
    {{- include "netpol.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: AmaltheaSession
      app.kubernetes.io/part-of: amaltheasession-operator
      # Allow remote access to amalthea's session reverse tunnel
      renku.io/remote-tunnel: allow
  policyTypes:
    - Ingress
  ingress:
    - from:
      # Allow ingress to the authentication proxy port on a v2 session
      - podSelector:
          matchLabels:
            app.kubernetes.io/name: ingress-nginx
        namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: ingress-nginx
      ports:
        - protocol: TCP
          # This port is hardcoded in Amalthea as the port for the reverse tunnel endpoint
          port: 65531