# Configuration file for deploying renku using an existing GitLab
# instance. Examples for gitlab.com and renkulab.io/gitlab are
# explicitly given.
# See
# https://github.com/SwissDataScienceCenter/renku/blob/master/helm-chart/README.rst
# and
# https://renku.readthedocs.io/en/latest/developer/example-configurations/external-gitlab)
# for instructions on how to use this values file.

variables:
  gitlabURL:                        &gitlabURL                          https://renkulab.io/gitlab  # Or another gitlab available at /gitlab
  gitlabClientId:                   &gitlabClientId                     # TODO: Put GitLab Application Id here!
  gitlabClientSecret:               &gitlabClientSecret                 # TODO: Put GitLab Secret here!
  gitlabRegistryHost:               &gitlabRegistryHost                 registry.renkulab.io  # Or the registry for this instance
  mainURL:                          &mainURL                            # TODO: Put the domain where renku is deployed here (i.e. example.com) - do not forget adding this in the keycloak section below
  notebookSessionTokenUrl:          &notebookSessionTokenUrl            https://renkulab.io/gitlab/oauth/token
  notebookSessionAuthUrl:           &notebookSessionAuthUrl             https://renkulab.io/gitlab/oauth/authorize
  notebookSessionOidcClientSecret:  &notebookSessionOidcClientSecret    # TODO: generate with openssl rand -hex 32

## TODO:  Edit the domain name below in the KEYCLOAK_FRONTEND_URL value
keycloak:
  extraEnv: |
    - name: KEYCLOAK_FRONTEND_URL
      value: https://<domain-name>/auth
    - name: DB_VENDOR
      value: postgres
    - name: DB_PORT
      value: "5432"
    - name:  PROXY_ADDRESS_FORWARDING
      value: "true"

global:
  useHTTPS: true
  renku:
    domain: *mainURL
  ## Comment out this block when using `renkulab.io/gitlab` or any other GitLab running under
  ## `<some-host-name>/gitlab`.
  ## Commenting this block will set the gitlab url prefix back to its default chart value (`/gitlab`).
  # gitlab:
  #   urlPrefix: ""

gitlab:
  enabled: false

notebooks:
  gitlab:
    url: *gitlabURL
    registry:
      host: *gitlabRegistryHost
  oidc:
    clientSecret: *notebookSessionOidcClientSecret
    tokenUrl: *notebookSessionTokenUrl
    authUrl: *notebookSessionAuthUrl
  sessionIngress:
    host: *mainURL

graph:
  gitlab:
    url: *gitlabURL

gateway:
  gitlabUrl: *gitlabURL
  gitlabClientId: *gitlabClientId
  gitlabClientSecret: *gitlabClientSecret

ingress:
  hosts:
    - *mainURL
