---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "renku.fullname" . }}-rclone-rcd
  labels:
    app: {{ template "renku.name" . }}-rclone-rcd
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: renku-rclone-rcd
    release: {{ .Release.Name }}

