flowchart TD
    ns[Notebook service]
    core[Core service]
    kg[Knowledge Graph]
    session[Interactive session]

    Clients --> |API| Gateway

    subgraph Clients
    UI
    CLI
    end

    subgraph Backends
    ns
    core
    kg
    GitLab
    end

    Gateway --> |proxy API| Backends
    GitLab --> |OIDC| Keycloak

    Gateway & session --> |OAuth| Keycloak


    Clients --> |connect| session

    ns --> |verify access| GitLab
    ns --> |create/destroy| session

    core --> |clone/push| GitLab

    kg <--> |clone/member sync/webhook| GitLab

    click ns "../services/notebooks-service.html"
