---
{{- if .Values.ingress.enabled -}}
{{- $kibanaFullName := include "kibana.fullname" . -}}
{{- $kibanaPort := .Values.kibana.service.port -}}
{{- $elasticsearchFullName := include "elasticsearch.fullname" . -}}
{{- $elasticsearchPort := 9200 -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ template "renku-logging.fullname" . }}
  labels:
    app: {{ template "renku-logging.name" . }}
    chart: {{ template "renku-logging.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- range $key, $value := .Values.ingress.labels }}
    {{ $key }}: "{{ $value }}"
    {{- end }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ . }}
    http:
      paths:
      - path: /kibana
        backend:
          serviceName: {{ $kibanaFullName }}
          servicePort: {{ $kibanaPort }}
      - path: /elasticsearch
        backend:
          serviceName: {{ $elasticsearchFullName }}
          servicePort: {{ $elasticsearchPort }}
  {{- end }}
{{- end }}
