---
{{- $db_password := randAlphaNum 64 }}
{{- $db_password_enc := $db_password | b64enc | quote }}
{{- $db_conn_uri := (printf "postgres://authz:%s@%s:5432/authz" $db_password (include "postgresql.fullname" .)) | b64enc | quote }}
{{- $api_key := randAlphaNum 64 | b64enc | quote }}

{{- $renkuFullname := include "renku.fullname" . -}}

{{- $secretName := cat $renkuFullname "-authz" | nospace }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace $secretName) }}
{{- if $secret }}
{{- $db_password_enc = index $secret.data "SPICEDB_POSTGRES_PASSWORD" }}
{{- $db_conn_uri = index $secret.data "SPICEDB_DATASTORE_CONN_URI" }}
{{- $api_key = index $secret.data "SPICEDB_GRPC_PRESHARED_KEY" }}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    app: {{ template "renku.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade,pre-rollback"
type: Opaque
data:
  SPICEDB_POSTGRES_PASSWORD: {{ $db_password_enc }}
  SPICEDB_DATASTORE_CONN_URI: {{ $db_conn_uri }}
  SPICEDB_GRPC_PRESHARED_KEY: {{ $api_key }}
