---
{{- if .Values.gitlab.enabled }}
{{- $db_password := default (randAlphaNum 64) .Values.global.gitlab.postgresPassword.value | b64enc | quote }}

{{- $renkuFullname := include "renku.fullname" . -}}

{{- if not .Values.global.gitlab.postgresPassword.value -}}
{{- $secretName := cat $renkuFullname "-gitlab-postgres" | nospace }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace $secretName) }}
{{- if $secret }}
{{- $db_password = index $secret.data "gitlab-postgres-password" }}
{{- end -}}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ template "renku.fullname" . }}-gitlab-postgres
  labels:
    app: {{ template "renku.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    {{ if or .Values.global.gitlab.postgresPassword.value -}}
    "helm.sh/hook": "pre-install,pre-upgrade,pre-rollback"
    {{- else -}}
    "helm.sh/hook": "pre-install"
    {{- end }}
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
data:
  gitlab-postgres-password: {{ $db_password }}
{{- end }}
