---
{{- $db_password := default (randAlphaNum 64) .Values.global.graph.tokenRepository.postgresPassword.value | b64enc | quote }}

{{- $renkuFullname := include "renku.fullname" . -}}

{{- if not .Values.global.graph.tokenRepository.postgresPassword.value -}}
{{- $secretName := cat $renkuFullname "-graph-token-postgres" | nospace }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace $secretName) }}
{{- if $secret }}
{{- $db_password = index $secret.data "graph-tokenRepository-postgresPassword" }}
{{- end -}}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ template "renku.fullname" . }}-graph-token-postgres
  labels:
    app: {{ template "renku.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade,pre-rollback"
type: Opaque
data:
  graph-tokenRepository-postgresPassword: {{ $db_password }}
