---
{{- $db_password := default (randAlphaNum 64) .Values.global.graph.dbEventLog.postgresPassword.value | b64enc | quote }}

{{- $renkuFullname := include "renku.fullname" . -}}

{{- if not .Values.global.graph.dbEventLog.postgresPassword.value -}}
{{- $secretName := cat $renkuFullname "-graph-db-postgres" | nospace }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace $secretName) }}
{{- if $secret }}
{{- $db_password = index $secret.data "graph-dbEventLog-postgresPassword" }}
{{- end -}}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ template "renku.fullname" . }}-graph-db-postgres
  labels:
    app: {{ template "renku.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    {{ if or .Values.global.graph.dbEventLog.postgresPassword.value -}}
    "helm.sh/hook": "pre-install,pre-upgrade,pre-rollback"
    {{- else -}}
    "helm.sh/hook": "pre-install"
    {{- end }}
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
data:
  graph-dbEventLog-postgresPassword: {{ $db_password }}
