---
{{- if .Values.keycloakx.enabled }}
{{- $postgresqlFullname := include "postgresql.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: renku-keycloak-postgres
  labels:
    app: {{ template "renku.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade,pre-rollback
    helm.sh/hook-delete-policy: before-hook-creation
type: Opaque
data:
  KC_DB_URL_HOST: {{ $postgresqlFullname | b64enc | quote }}
  KC_DB_URL_DATABASE: {{ .Values.global.keycloak.postgresDatabase | b64enc | quote }}
  KC_DB_USENAME: {{ .Values.global.keycloak.postgresUser | b64enc | quote }}
  KC_DB_PASSWORD: {{ default (randAlphaNum 64) .Values.global.keycloak.postgresPassword.value | b64enc | quote }}
{{- end }}
