---
{{- $db_password := default (randAlphaNum 64) .Values.global.keycloak.postgresPassword.value | b64enc | quote }}

{{- if not .Values.global.keycloak.postgresPassword.value }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace "renku-keycloak-postgres") }}
{{- if $secret }}
{{- $db_password = index $secret.data "DB_PASSWORD" }}
{{- end -}}
{{- end -}}

{{- if .Values.keycloak.enabled }}
{{- $postgresqlFullname := include "postgresql.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: renku-keycloak-postgres
  labels:
    app: {{ template "renku.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    {{ if or .Values.global.keycloak.postgresPassword.value -}}
    "helm.sh/hook": "pre-install,pre-upgrade,pre-rollback"
    {{- else -}}
    "helm.sh/hook": "pre-install"
    {{- end }}
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
data:
  DB_ADDR: {{ $postgresqlFullname | b64enc | quote }}
  DB_DATABASE: {{ .Values.global.keycloak.postgresDatabase | b64enc | quote }}
  DB_USER: {{ .Values.global.keycloak.postgresUser | b64enc | quote }}
  DB_PASSWORD: {{ $db_password }}
{{- end }}
