---
{{- if .Values.keycloak.enabled }}
{{- $kc_password := default (randAlphaNum 64) .Values.global.keycloak.password.value | b64enc | quote }}

{{- if not .Values.global.keycloak.password.value }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace "keycloak-password-secret") }}
{{- if $secret }}
{{- $kc_password = index $secret.data "KEYCLOAK_PASSWORD" }}
{{- end -}}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: keycloak-password-secret
  labels:
    app: {{ template "renku.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    {{ if or .Values.global.keycloak.password.value -}}
    "helm.sh/hook": "pre-install,pre-upgrade,pre-rollback"
    {{- else -}}
    "helm.sh/hook": "pre-install"
    {{- end }}
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
data:
  KEYCLOAK_USER: {{ .Values.global.keycloak.user | b64enc | quote }}
  KEYCLOAK_PASSWORD: {{ $kc_password }}
{{- end }}
