---
{{- if .Values.keycloakx.createDemoUser }}

{{- $keycloakDemoUserPassword := randAlphaNum 64 | b64enc | quote }}

{{- $renkuFullname := include "renku.fullname" . -}}
{{- $secretName := cat $renkuFullname "-kc-demo-user" | nospace }}

{{- $secret := (lookup "v1" "Secret" .Release.Namespace $secretName) }}
{{- if $secret }}
{{- $keycloakDemoUserPassword = index $secret.data "keycloakDemoUserPassword" }}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    app: {{ template "renku.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade,pre-rollback"
    {{- if .Values.argoCD }}
    "argocd.argoproj.io/hook": PreSync
    {{- end }}
type: Opaque
data:
  # A password for a demo user for keycloak
  keycloakDemoUserPassword: {{ $keycloakDemoUserPassword }}
{{- end }}
