---
{{- if .Values.keycloakx.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: renku-keycloak-postgres
  labels:
    app: {{ template "renku.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade,pre-rollback
    helm.sh/hook-delete-policy: before-hook-creation
type: Opaque
data:
{{- include "keycloak.postgres-secret" . | nindent 2 }}
{{- end }}
