---
{{- if .Values.keycloakx.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-password-secret
  labels:
    app: {{ template "renku.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade,pre-rollback
    helm.sh/hook-delete-policy: before-hook-creation
type: Opaque
data:
  KEYCLOAK_ADMIN: {{ .Values.global.keycloak.user | b64enc | quote }}
  KEYCLOAK_ADMIN_PASSWORD: {{ default (randAlphaNum 64) .Values.global.keycloak.password.value | b64enc | quote }}
{{- end }}
