{{- if .Values.gitlab.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-post-install-gitlab"
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "20"
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  template:
    metadata:
      name: "{{.Release.Name}}-post-install-gitlab"
      labels:
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    spec:
      restartPolicy: Never
      containers:
        - name: configure-gitlab
          image: "postgres:11.11"
          command: ["/bin/bash", "/scripts/init-gitlab.sh"]
          volumeMounts:
            - name: init
              mountPath: /scripts
              readOnly: true
          env:
          - name: PGDATABASE
            value: {{ .Values.global.gitlab.postgresDatabase }}
          - name: PGUSER
            value: {{ .Values.global.gitlab.postgresUser }}
          - name: PGHOST
            value: {{ template "postgresql.fullname" . }}
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "postgresql.fullname" . }}-password
                key: gitlab-postgres-password
          - name: RENKU_AUTH_GITLAB_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ template "renku.fullname" . }}
                key: renku-auth-gitlab-client-secret
      volumes:
        - name: init
          configMap:
            name: {{ template "renku.fullname" . }}
{{- end }}
