---
{{- $db_password := randAlphaNum 64 | b64enc | quote }}

{{- $secret := lookup "v1" "Secret" .Release.Namespace .Values.global.db.common.passwordSecretName }}
{{- if $secret }}
{{- $db_password = index $secret.data "password" }}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.db.common.passwordSecretName }}
  labels:
    app: {{ template "renku.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade,pre-rollback"
type: Opaque
data:
  password: {{ $db_password }}
