---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "renku.fullname" . }}
  labels:
    app: {{ template "renku.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
{{- if .Values.keycloakx.enabled }}
  clients: {{ include "renku.keycloak.clients" .  | b64enc | quote }}
  users: {{ include "renku.keycloak.users" . | b64enc | quote }}
{{- end }}

{{- if .Values.tests.users_json }}
  users.json: {{ .Values.tests.users_json | toJson | b64enc | quote }}
{{- end }}

  gateway-gitlab-client-secret: {{ required "Fill in .Values.global.gateway.gitlabClientSecret with `openssl rand -hex 32`" .Values.global.gateway.gitlabClientSecret | b64enc | quote }}


{{- if and (eq .Values.redis.install true) (eq .Values.redis.createSecret true) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.redis.auth.existingSecret }}
  labels:
    app: {{ template "renku.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{ .Values.redis.auth.existingSecretPasswordKey }}: {{ .Values.redis.password | b64enc | quote }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.db.common.passwordSecretName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace .Values.global.db.common.passwordSecretName) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $secretVal := (get $secretData "password") | default (randAlphaNum 32 | b64enc) }}
  password: {{ $secretVal | quote }}
