---
{{- $data_service_kc_client_secret := (randAlphaNum 64) | b64enc | quote }}

{{- $renku_secret := lookup "v1" "Secret" .Release.Namespace (include "renku.fullname" .) }}
{{- if and $renku_secret $renku_secret.data }}
{{- $data_service_kc_client_secret_test := index $renku_secret.data "dataServiceKeycloakClientSecret" }}
{{- if $data_service_kc_client_secret_test }}
{{- $data_service_kc_client_secret = $data_service_kc_client_secret_test }}
{{- end -}}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ template "renku.fullname" . }}
  labels:
    app: {{ template "renku.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    # If "keep" resource policy is removed the secret is deleted post upgrade see https://github.com/helm/helm/issues/8420
    "helm.sh/resource-policy": keep
    "helm.sh/hook": "pre-install,pre-upgrade,pre-rollback"
    {{- if .Values.argoCD }}
    "argocd.argoproj.io/hook": PreSync
    {{- end }}
type: Opaque
data:
  {{- if .Values.tests.users_json }}
  users.json: {{ .Values.tests.users_json | toJson | b64enc | quote }}
  {{- end }}
  dataServiceKeycloakClientSecret: {{ $data_service_kc_client_secret }}

{{- if and (eq .Values.redis.install true) (eq .Values.redis.createSecret true) }}
---
{{ $redisPassword := .Values.redis.password | default (randAlphaNum 64) | b64enc | quote }}
{{- if not .Values.redis.password -}}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace .Values.redis.auth.existingSecret) }}
{{- if $secret }}
{{- $redisPassword = index $secret.data .Values.redis.auth.existingSecretPasswordKey }}
{{- end -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.redis.auth.existingSecret }}
  labels:
    app: {{ template "renku.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    # If "keep" resource policy is removed the secret is deleted post upgrade see https://github.com/helm/helm/issues/8420
    "helm.sh/resource-policy": keep
    "helm.sh/hook": "pre-install,pre-upgrade,pre-rollback"
    {{- if .Values.argoCD }}
    "argocd.argoproj.io/hook": PreSync
    {{- end }}
type: Opaque
data:
  {{ .Values.redis.auth.existingSecretPasswordKey }}: {{ $redisPassword }}
{{- end }}
