---
{{- $data_service_kc_client_secret := randAlphaNum 64 | b64enc | quote }}

{{- $renku_secret := lookup "v1" "Secret" .Release.Namespace (include "renku.fullname" .) }}
{{- if $renku_secret }}
{{- $data_service_kc_client_secret = index $renku_secret.data "dataServiceKeycloakClientSecret" }}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ template "renku.fullname" . }}
  labels:
    app: {{ template "renku.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade,pre-rollback"
type: Opaque
data:
  {{- if .Values.tests.users_json }}
  users.json: {{ .Values.tests.users_json | toJson | b64enc | quote }}
  {{- end }}
  dataServiceKeycloakClientSecret: {{ $data_service_kc_client_secret }}


{{- if and (eq .Values.redis.install true) (eq .Values.redis.createSecret true) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.redis.auth.existingSecret }}
  labels:
    app: {{ template "renku.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{ .Values.redis.auth.existingSecretPasswordKey }}: {{ .Values.redis.password | b64enc | quote }}
{{- end }}
