---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "renku.fullname" . }}
  labels:
    app: {{ template "renku.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
{{- if .Values.keycloak.enabled }}
  clients: {{ include "renku.keycloak.clients" .  | b64enc | quote }}
  users: {{ include "renku.keycloak.users" . | b64enc | quote }}
{{- end }}

{{- if .Values.tests.users_json }}
  users.json: {{ .Values.tests.users_json | toJson | b64enc | quote }}
{{- end }}

  gateway-gitlab-client-secret: {{ required "Fill in .Values.global.gateway.gitlabClientSecret with `openssl rand -hex 32`" .Values.global.gateway.gitlabClientSecret | b64enc | quote }}


{{- if and (eq .Values.redis.install true) (eq .Values.redis.createSecret true) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.redis.existingSecret }}
  labels:
    app: {{ template "renku.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{ .Values.redis.existingSecretPasswordKey }}: {{ .Values.redis.password | b64enc | quote }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-rabbitmq-admin"
  labels:
    app: {{ template "renku.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
stringData:
  config.yaml: |
    admin:
      {{- if .Values.global.rabbitmq.external.disabled }}
      username: {{ .Values.rabbitmq.auth.username | quote }}
      password: {{ .Values.rabbitmq.auth.password | quote }}
      {{- else }}
      username: {{ .Values.global.rabbitmq.external.admin.username | quote }}
      password: {{ .Values.global.rabbitmq.external.admin.password | quote }}
      {{- end }}
    users:
      {{ .Values.global.rabbitmq.users | toYaml | nindent 6 }}
