---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "renku.fullname" . }}
  labels:
    app: {{ template "renku.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
{{- if .Values.keycloak.enabled }}
  clients: {{ include "renku.keycloak.clients" .  | b64enc | quote }}
  users: {{ include "renku.keycloak.users" . | b64enc | quote }}
{{- end }}

{{- if .Values.tests.users_json }}
  users.json: {{ .Values.tests.users_json | toJson | b64enc | quote }}
{{- end }}

  gateway-gitlab-client-secret: {{ required "Fill in .Values.global.gateway.gitlabClientSecret with `openssl rand -hex 32`" .Values.global.gateway.gitlabClientSecret | b64enc | quote }}


{{- if and (eq .Values.redis.install true) (eq .Values.redis.createSecret true) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  labels:
    app: {{ template "renku.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  # Note: just temporarily adding a default here to test the PR, as github actions don't allow password
  # outputs as a means of passing variables between workflow steps.
  redis-password: {{ .Values.redis.password  | default "removeme" | b64enc | quote }}
{{- end }}
