apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-init-ssh-proxy-session-keys-rev{{ .Release.Revision }}-{{ randAlphaNum 5 | lower }}"
  labels:
    app: ssh-proxy-session-keys
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ template "renku.chart" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,pre-rollback
spec:
  template:
    metadata:
      name: {{ .Release.Name }}-ssh-proxy-session-keys
      labels:
        app: ssh-proxy-session-keys
        heritage: {{ .Release.Service }}
        release: {{ .Release.Name }}
        chart: {{ template "renku.chart" . }}
    spec:
      restartPolicy: Never
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: generate-ssh-proxy-session-keys
          image: "{{ .Values.sshProxySessionKeys.image.repository }}:{{ .Values.sshProxySessionKeys.image.tag }}"
          args: [ "ssh_proxy_session_keys.py" ]
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          env:
            - name: K8S_NAMESPACE
              value: {{ .Release.Namespace }}
            - name: RENKU_FULLNAME
              value: {{ template "renku.fullname" . }}
      serviceAccountName: {{ template "renku.fullname" . }}-ssh-proxy-session-keys
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "renku.fullname" . }}-ssh-proxy-session-keys
  labels:
    app: {{ template "renku.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,pre-rollback
    "helm.sh/hook-weight": "-5"
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - create
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "renku.fullname" . }}-ssh-proxy-session-keys
  labels:
    app: {{ template "renku.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,pre-rollback
    "helm.sh/hook-weight": "-5"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "renku.fullname" . }}-ssh-proxy-session-keys
  labels:
    app: {{ template "renku.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,pre-rollback
    "helm.sh/hook-weight": "-5"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "renku.fullname" . }}-ssh-proxy-session-keys
subjects:
  - kind: ServiceAccount
    name: {{ template "renku.fullname" . }}-ssh-proxy-session-keys
    namespace: {{ .Release.Namespace }}
