{{- if hasKey .Values "keycloak" -}}
{{- fail "Values to configure Keycloak should be under `keycloakx`." -}}
{{- end -}}
{{- if .Values.keycloakx.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-init-keycloak-realms-rev{{ .Release.Revision }}-{{ randAlphaNum 5 | lower }}"
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ template "renku.chart" . }}
spec:
  template:
    metadata:
      name: "{{.Release.Name}}-init-keycloak-realms"
      labels:
        heritage: {{ .Release.Service }}
        release: {{ .Release.Name }}
        chart: {{ template "renku.chart" . }}
    spec:
      restartPolicy: Never
      initContainers:
        {{- include "certificates.initContainer" . | nindent 8 }}
      containers:
        - name: init-keycloak
          image: "{{ .Values.keycloakx.initRealm.image.repository }}:{{ .Values.keycloakx.initRealm.image.tag }}"
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false
            runAsNonRoot: true
          command: ["python"]
          args: [
            "/app/init-realm.py",
            "--admin-user=$(KEYCLOAK_ADMIN_USER)",
            "--admin-password=$(KEYCLOAK_ADMIN_PASSWORD)",
            "--keycloak-url=$(KEYCLOAK_URL)",
            "--force"
          ]

          volumeMounts:
            {{- include "certificates.volumeMounts.system" . | nindent 12 }}

          env:
            - name: KEYCLOAK_URL
              value: {{ include "renku.keycloakUrl" . | quote }}
            - name: RENKU_BASE_URL
              value: {{ include "renku.baseUrl" . | quote }}
            - name: KEYCLOAK_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: keycloak-password-secret
                  key: KEYCLOAK_ADMIN
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-password-secret
                  key: KEYCLOAK_ADMIN_PASSWORD
            - name: CREATE_DEMO_USER
              value: {{ .Values.keycloakx.createDemoUser | toString | lower | quote }}
            {{- if .Values.keycloakx.createDemoUser }}
            - name: DEMO_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ cat (include "renku.fullname" .) "-kc-demo-user" | nospace }}
                  key: keycloakDemoUserPassword
            {{- end }}
            - name: INTERNAL_GITLAB_ENABLED
              value: "false"
            - name: RENKU_KC_CLIENT_ID
              value: renku
            - name: RENKU_KC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ cat (include "renku.fullname" .) "-gateway" | nospace }}
                  key: oidcClientSecret
            - name: RENKU_KC_CLIENT_PUBLIC
              value: "false"
            - name: RENKU_KC_CLIENT_OAUTH_FLOW
              value: "authorization_code"
            - name: CLI_KC_CLIENT_ID
              value: renku-cli
            - name: CLI_KC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ cat (include "renku.fullname" .) "-gateway" | nospace }}
                  key: cliClientSecret
            - name: CLI_KC_CLIENT_PUBLIC
              value: "true"
            - name: CLI_KC_CLIENT_ATTRIBUTES
              value: '{"access.token.lifespan": "86400", "oauth2.device.authorization.grant.enabled": true, "oauth2.device.polling.interval": "5"}'
            - name: CLI_KC_CLIENT_OAUTH_FLOW
              value: "device"
            - name: UI_KC_CLIENT_ID
              value: "renku-ui"
            - name: UI_KC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ cat (include "renku.fullname" .) "-gateway" | nospace }}
                  key: uiserverClientSecret
            - name: UI_KC_CLIENT_PUBLIC
              value: "false"
            - name: UI_KC_CLIENT_OAUTH_FLOW
              value: "authorization_code"
            - name: NOTEBOOKS_KC_CLIENT_ID
              value: {{ .Values.notebooks.oidc.clientId | default "renku-jupyterserver" | quote }}
            - name: NOTEBOOKS_KC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ cat (include "renku.fullname" .) "-gateway" | nospace }}
                  key: notebooksClientSecret
            - name: NOTEBOOKS_KC_CLIENT_PUBLIC
              value: "false"
            - name: NOTEBOOKS_KC_CLIENT_OAUTH_FLOW
              value: "authorization_code"
            - name: SWAGGER_KC_CLIENT_ID
              value: swagger
            - name: SWAGGER_KC_CLIENT_PUBLIC
              value: "true"
            - name: SWAGGER_KC_CLIENT_OAUTH_FLOW
              value: "authorization_code"
            - name: SWAGGER_KC_CLIENT_ATTRIBUTES
              value: '{"pkce.code.challenge.method": "S256"}'
            - name: DATASERVICE_KC_CLIENT_ID
              value: {{ include "renku.dataService.keycloak.clientId" . | quote }}
            - name: DATASERVICE_KC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "renku.fullname" . }}
                  key: dataServiceKeycloakClientSecret
            - name: DATASERVICE_KC_CLIENT_PUBLIC
              value: "false"
            - name: DATASERVICE_KC_CLIENT_OAUTH_FLOW
              value: "client_credentials"
            - name: "DATASERVICE_KC_CLIENT_SERVICE_ACCOUNT_ROLES"
              value: '["view-users", "query-users", "view-events", "view-realm"]'
            - name: PYTHONUNBUFFERED
              value: "0"
            {{- include "certificates.env.python" . | nindent 12 }}

      volumes:
        {{- include "certificates.volumes" . | nindent 8 -}}
{{- end }}
