apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-init-postgres-renku-rev{{ .Release.Revision }}-{{ randAlphaNum 5 | lower }}"
  labels:
    app: postgres-setup
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ template "renku.chart" . }}
spec:
  template:
    metadata:
      name: {{ .Release.Name }}-init-postgres-renku
      labels:
        app: postgres-setup
        heritage: {{ .Release.Service }}
        release: {{ .Release.Name }}
        chart: {{ template "renku.chart" . }}
    spec:
      restartPolicy: Never
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: initialize-postgres-renku
          image: "{{ .Values.initDb.image.repository }}:{{ .Values.initDb.image.tag }}"
          args: [ "renku_db_init.py" ]
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          env:
            - name: DB_HOST
              value: {{ template "postgresql.fullname" . }}
            - name: DB_ADMIN_USERNAME
              {{ if .Values.global.externalServices.postgresql.enabled }}
              value: {{ .Values.global.externalServices.postgresql.username }}
              {{- else -}}
              value: {{ .Values.postgresql.auth.username }}
              {{- end }}
            {{- if not .Values.global.externalServices.postgresql.enabled }}
            - name: DB_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ template "postgresql.fullname" . }}"
                  key: postgres-password
            {{- else if .Values.global.externalServices.postgresql.password }}
            - name: DB_ADMIN_PASSWORD
              value: {{ .Values.global.externalServices.postgresql.password }}
            {{- else if .Values.global.externalServices.postgresql.existingSecret }}
            - name: DB_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.externalServices.postgresql.existingSecret }}
                  key: postgres-password
            {{- end }}
            - name: RENKU_DB_USERNAME
              value: {{ .Values.global.db.common.username | quote }}
            - name: RENKU_DB_NAME
              value: renku
            - name: RENKU_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.db.common.passwordSecretName }}
                  key: password
