apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-init-postgres-renku-rev{{ .Release.Revision }}-{{ randAlphaNum 5 | lower }}"
  labels:
    app: postgres-setup
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ template "renku.chart" . }}
spec:
  template:
    metadata:
      name: {{ .Release.Name }}-init-postgres-renku
      labels:
        app: postgres-setup
        heritage: {{ .Release.Service }}
        release: {{ .Release.Name }}
        chart: {{ template "renku.chart" . }}
    spec:
      restartPolicy: Never
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: initialize-postgres-renku
          image: "{{ .Values.initDb.image.repository }}:{{ .Values.initDb.image.tag }}"
          args: [ "renku_db_init.py" ]
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          env:
            {{- include "renku.pgAdminEnv" . | nindent 12 }}
            - name: RENKU_DB_USERNAME
              value: {{ .Values.global.db.common.username | quote }}
            - name: RENKU_DB_NAME
              value: renku
            - name: RENKU_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.db.common.passwordSecretName }}
                  key: password
