apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-init-postgres-authz-rev{{ .Release.Revision }}-{{ randAlphaNum 5 | lower }}"
  labels:
    app: postgres-setup
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ template "renku.chart" . }}
spec:
  template:
    metadata:
      name: {{ .Release.Name }}-init-postgres-authz
      labels:
        app: postgres-setup
        heritage: {{ .Release.Service }}
        release: {{ .Release.Name }}
        chart: {{ template "renku.chart" . }}
    spec:
      restartPolicy: Never
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: initialize-postgres-authz
          image: "{{ .Values.initDb.image.repository }}:{{ .Values.initDb.image.tag }}"
          args: [ "authz_db_init.py" ]
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          env:
            {{- include "renku.pgAdminEnv" . | nindent 12 }}
            - name: AUTHZ_DB_USERNAME
              value: authz
            - name: AUTHZ_DB_NAME
              value: authz
            - name: AUTHZ_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "renku.fullname" . }}-authz
                  key: SPICEDB_POSTGRES_PASSWORD
