{{- if .Values.gitlab.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-init-postgres-gitlab-rev{{ .Release.Revision }}-{{ randAlphaNum 5 | lower }}"
  labels:
    app: postgres-setup
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ template "renku.chart" . }}
spec:
  template:
    metadata:
      name: {{ .Release.Name }}-init-postgres-gitlab
      labels:
        app: postgres-setup
        heritage: {{ .Release.Service }}
        release: {{ .Release.Name }}
        chart: {{ template "renku.chart" . }}
    spec:
      restartPolicy: Never
      containers:
        - name: initialize-postgres-renku
          image: "{{ .Values.initDb.image.repository }}:{{ .Values.initDb.image.tag }}"
          args: [ "gitlab_db_init.py" ]
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false
            runAsNonRoot: true
          env:
            - name: DB_HOST
              value: {{ template "postgresql.fullname" . }}
            - name: DB_ADMIN_USERNAME
              {{ if .Values.global.externalServices.postgresql.enabled }}
              value: {{ .Values.global.externalServices.postgresql.username }}
              {{- else -}}
              value: {{ .Values.postgresql.auth.username }}
              {{- end }}
            {{- if not .Values.global.externalServices.postgresql.enabled }}
            - name: DB_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ template "postgresql.fullname" . }}"
                  key: postgres-password
            {{- else if .Values.global.externalServices.postgresql.password }}
            - name: DB_ADMIN_PASSWORD
              value: {{ .Values.global.externalServices.postgresql.password }}
            {{- else if .Values.global.externalServices.postgresql.existingSecret }}
            - name: DB_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.externalServices.postgresql.existingSecret }}
                  key: postgres-password
            {{- end }}
            - name: GITLAB_ENABLED
              value: {{ .Values.gitlab.enabled | quote }}
            - name: GITLAB_OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ cat (include "renku.fullname" .) "-gateway" | nospace }} 
                  key: gitlabClientSecret
            - name: GITLAB_OAUTH_CLIENT_ID
              value: {{ .Values.gateway.gitlabClientId | default .Values.global.gateway.gitlabClientId | quote }}
            - name: GITLAB_DB_USERNAME
              value: {{ .Values.global.gitlab.postgresUser | quote }}
            - name: GITLAB_DB_NAME
              value: {{ .Values.global.gitlab.postgresDatabase | quote }}
            - name: GITLAB_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "renku.fullname" . }}-gitlab-postgres
                  key: gitlab-postgres-password
            - name: GITLAB_URL
              value: {{ .Values.global.gitlab.url | quote }}
            - name: RENKU_URL
              value: "{{ template "renku.http" . }}://{{ .Values.global.renku.domain }}"
{{- end }}
