{{- range $version := .Values.versions }}
---
{{- if $.Capabilities.APIVersions.Has "autoscaling/v2" }}
apiVersion: autoscaling/v2
{{- else if $.Capabilities.APIVersions.Has "autoscaling/v2beta2" }}
apiVersion: autoscaling/v2beta2
{{- else if $.Capabilities.APIVersions.Has "autoscaling/v2beta1" }}
apiVersion: autoscaling/v2beta1
{{- else }}
  {{- fail "ERROR: You must have at least autoscaling/v2beta1 to use HorizontalPodAutoscaler" }}
{{- end }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "renku-core.fullname" $ }}-{{ $version.name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "renku-core.fullname" $ }}-{{ $version.name }}
  minReplicas: {{ $.Values.horizontalPodAutoscaling.minReplicas }}
  maxReplicas: {{ $.Values.horizontalPodAutoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ $.Values.horizontalPodAutoscaling.averageMemoryUtilization }}
{{ end }}
