{{- if not .Values.excludeLegacyServices }}
{{- range $version := .Values.global.core.versions }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "renku-core.fullname" $ }}-{{ $version.name }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/deploymentVersion: {{ $version.name }}
{{ end }}
{{- end }}
