import type { SidebarsConfig, SidebarItemConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

function createSectionDivider(sectionName: string,): {} {
  return {
    type: 'html',
    value: `
    <div class="sidebar-section-header">
      <span class="sidebar-section-text">${sectionName}</span>
      <div class="sidebar-section-line"></div>
    </div>
    `,
    className: 'sidebar-section-divider',
  };
}

const sidebars: SidebarsConfig = {
  users: [
    {
      type: 'autogenerated',
      dirName: '10-users'
    },
    // { type: 'autogenerated', dirName: '10-users/20-getting-started' },
  ],
  admins: [
    {
      type: 'autogenerated',
      dirName: '20-admins'
    },
  ],

};

export default sidebars;
