import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  users: [
    { type: 'autogenerated', dirName: '01-users' },
    // Add manual links after autogenerated content
    {
      type: 'category',
      label: 'Community',
      items: [
        {
          type: 'html',
          value: `
            <div class="sidebar-section-header">
              <span class="sidebar-section-text">CONCEPTS</span>
              <div class="sidebar-section-line"></div>
            </div>
          `,
          className: 'sidebar-section-divider',
        },
        {
          type: 'link',
          label: 'Contact Us',
          href: 'https://example.com',
        },
        {
          type: 'link',
          label: 'Community Portal',
          href: 'https://example.com',
        },
        {
          type: 'link',
          label: 'Renku Blog',
          href: 'https://blog.renkulab.io',
        },
        {
          type: 'link',
          label: 'Newsletter',
          href: 'https://example.com',
        },
        {
          type: 'link',
          label: 'Community Events',
          href: 'https://example.com',
        },
      ],
    },
  ],
  admins: [
    { type: 'autogenerated', dirName: '02-admins' },
  ],

};

export default sidebars;
