{{- if and .Values.notebooks.serverOptions .Values.notebooks.serverDefaults -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "renku.fullname" . }}-server-options
  labels:
    app.kubernetes.io/name: {{ template "renku.name" . }}
    {{- include "dataservice.labels" . | nindent 4 }}
data:
  server_options.json: |
    {{ .Values.notebooks.serverOptions | default dict | toJson }}
  server_defaults.json: |
    {{ toJson .Values.notebooks.serverDefaults }}
{{- end -}}
