{{- if and .Values.notebooks.serverOptions .Values.notebooks.serverDefaults -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "renku.fullname" . }}-server-options
  labels:
    app: {{ template "renku.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  server_options.json: |
    {{ .Values.notebooks.serverOptions | default dict | toJson }}
  server_defaults.json: |
    {{ toJson .Values.notebooks.serverDefaults }}
{{- end -}}
