{{- if .Values.dataService.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "renku.fullname" . }}-data-tasks
  labels:
    app: {{ template "renku.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
{{- if .Values.dataService.dataTasks.enableResourceRequestTracking }}
  - apiGroups:
      - ""
    resources:
      - pods
      - persistentvolumeclaims
    verbs:
      - get
      - list
{{- end }}
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - create
      - get
      - list
      - watch
      - patch
      - delete
  - apiGroups:
      - amalthea.dev
    resources:
      - amaltheasessions
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "renku.fullname" . }}-data-tasks
  labels:
    app: {{ template "renku.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "renku.fullname" . }}-data-tasks
subjects:
  - kind: ServiceAccount
    name: {{ template "renku.fullname" . }}-data-tasks
    namespace: {{ .Release.Namespace }}
{{- if .Values.dataService.dataTasks.enableResourceRequestTracking }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "renku.fullname" . }}-data-tasks-cluster-role
  labels:
    app: {{ template "renku.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "renku.fullname" . }}-data-tasks
subjects:
  - kind: ServiceAccount
    name: {{ template "renku.fullname" . }}-data-tasks
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "renku.fullname" . }}-data-tasks
  labels:
    app: {{ template "renku.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
{{- end }}
{{- end }}
