{{- if .Values.dataService.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "renku.fullname" . }}-data-service
  labels:
    app: {{ template "renku.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
  - apiGroups:
      - ""
    resources:
      - resourcequotas
    verbs:
      - get
      - list
      - patch
      - delete
      - create
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
      - services
      - endpoints
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
      - secrets
    verbs:
      - delete
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - get
      - list
      - watch
      - patch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - update
      - delete
      - patch
  - apiGroups:
      - {{ .Values.amalthea.crdApiGroup }}
    resources:
      - {{ .Values.amalthea.crdNames.plural }}
    verbs:
      - create
      - update
      - delete
      - patch
      - list
      - get
      - watch
  - apiGroups:
      - amalthea.dev
    resources:
      - amaltheasessions
    verbs:
      - create
      - update
      - delete
      - patch
      - list
      - get
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "renku.fullname" . }}-data-service
  labels:
    app: {{ template "renku.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
  - apiGroups:
      - "scheduling.k8s.io"
    resources:
      - priorityclasses
    verbs:
      - get
      - list
      - patch
      - delete
      - create
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "renku.fullname" . }}-data-service
  labels:
    app: {{ template "renku.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "renku.fullname" . }}-data-service
  labels:
    app: {{ template "renku.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "renku.fullname" . }}-data-service
subjects:
  - kind: ServiceAccount
    name: {{ template "renku.fullname" . }}-data-service
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "renku.fullname" . }}-data-service
  labels:
    app: {{ template "renku.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "renku.fullname" . }}-data-service
subjects:
  - kind: ServiceAccount
    name: {{ template "renku.fullname" . }}-data-service
    namespace: {{ .Release.Namespace }}
{{- end -}}
