{{- if .Values.dataService.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "renku.fullname" . }}-data-service
  labels:
    app: {{ template "renku.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
      - services
      - endpoints
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
      - secrets
    verbs:
      - delete
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - get
      - list
      - watch
      - patch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - update
      - delete
      - patch
  - apiGroups:
      - amalthea.dev
    resources:
      - amaltheasessions
    verbs:
      - create
      - update
      - delete
      - patch
      - list
      - get
      - watch
  {{- if .Values.dataService.imageBuilders.enabled }}
  - apiGroups:
      - shipwright.io
    resources:
      - buildruns
    verbs:
      - create
      - update
      - delete
      - patch
      - list
      - get
      - watch
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "renku.fullname" . }}-data-service
  labels:
    app: {{ template "renku.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "renku.fullname" . }}-data-service
subjects:
  - kind: ServiceAccount
    name: {{ template "renku.fullname" . }}-data-service
    namespace: {{ .Release.Namespace }}
{{- end -}}
