apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "renku.fullname" . }}-data-service
  labels:
    app.kubernetes.io/name: {{ template "renku.name" . }}
    {{- include "dataservice.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "renku.fullname" . }}-k8s-watcher
  labels:
    app.kubernetes.io/name: {{ template "renku.name" . }}
    {{- include "dataservice.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "renku.fullname" . }}-data-tasks
  labels:
    app.kubernetes.io/name: {{ template "renku.name" . }}
    {{- include "dataservice.labels" . | nindent 4 }}
