apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "renku.fullname" . }}-data-service
  labels:
    app: {{ template "renku.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "renku.fullname" . }}-k8s-watcher
  labels:
    app: {{ template "renku.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
