{{- if or (gt (int .Values.secretsStorage.replicaCount) 1) (and .Values.secretsStorage.autoscaling.enabled (gt (int .Values.secretsStorage.autoscaling.minReplicas) 1)) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ template "renku.fullname" . }}-secrets-storage
  labels:
    app.kubernetes.io/name: renku-secrets-storage
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: secrets-storage
    app.kubernetes.io/part-of: renku
    chart: {{ template "renku.chart" . }}
    heritage: {{ .Release.Service }}
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      app.kubernetes.io/name: renku-secrets-storage
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
