{{- $namespaces := list -}}
{{ if .Values.notebooks.sessionsNamespace }}
{{- $namespaces = list .Release.Namespace .Values.notebooks.sessionsNamespace | uniq -}}
{{ else }}
{{- $namespaces = list .Release.Namespace -}}
{{ end }}
{{ range $namespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "renku.fullname" $ }}-secrets-storage
  namespace: {{ . }}
  labels:
    app: {{ template "renku.name" $ }}
    chart: {{ template "renku.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "renku.fullname" $ }}-secrets-storage
  labels:
    app: {{ template "renku.name" $ }}
    chart: {{ template "renku.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "renku.fullname" $ }}-secrets-storage
subjects:
  - kind: ServiceAccount
    name: {{ template "renku.fullname" $ }}-secrets-storage
    namespace: {{ $.Release.Namespace }}
{{ end }}
