apiVersion: v1
kind: Secret
metadata:
  name: {{ template "renku.fullname" . }}-secrets-storage
  labels:
    app: renku-secrets-storage
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade,pre-rollback"
type: Opaque
data:
  encryptionKey: {{ required "Fill in .Values.secretsStorage.encryptionKey with `openssl rand 32 | base64`" .Values.secretsStorage.encryptionKey | quote }}
