apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "renku.fullname" . }}-secrets-storage
  labels:
    app.kubernetes.io/name: {{ template "renku.name" . }}
    {{- include "secretsstorage.labels" $ | nindent 4 }}
