apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "renku.fullname" . }}-secrets-storage
  labels:
    app: {{ template "renku.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
